using System;
using System.Collections.Generic;

namespace Maelstrom.ContentModel
{
    /// <summary>
    /// Serializable mirrors of unity/Assets/Resources/maelstrom-content.json.
    ///
    /// That file is GENERATED by tools/build-content.mjs from content/*.json -
    /// the same source the web build uses - so the two runtimes cannot disagree
    /// about what anything is made of. Do not edit it by hand; edit content/ and
    /// re-run `npm run build:content`.
    ///
    /// Shapes here are constrained by JsonUtility: no dictionaries, no nullable
    /// primitives, no top-level arrays. The build step flattens every
    /// id-to-quantity map into an array of pairs for exactly this reason.
    ///
    /// NOTE ON THIS DIRECTORY: the GDD's PC project is Unreal Engine 5.8. This
    /// C# tree exists because the repository it was first ported from was a
    /// Unity prototype, which turned out to be a different project. It is kept
    /// only so the generated bundle has a matching reader; it mirrors canon, but
    /// canon does not target Unity.
    /// </summary>
    [Serializable]
    public class ContentBundleJson
    {
        public int version;
        public float unitsPerPixel = 12f;
        public ProgressionJson progression;
        public ColiseumJson coliseum;
        public CraftingJson crafting;
        public WavesJson waves;
        public List<ElementJson> elements = new List<ElementJson>();
        public List<MaterialJson> materials = new List<MaterialJson>();
        public List<BiomeJson> biomes = new List<BiomeJson>();
        public List<AlchemyCombinationJson> alchemy = new List<AlchemyCombinationJson>();
        public List<EnemyJson> enemies = new List<EnemyJson>();
        public List<TutorialStepJson> tutorial = new List<TutorialStepJson>();
    }

    // ------------------------------------------------------------- elements

    /// <summary>
    /// One of the ten invented elements. Never real chemistry: the symbol is
    /// always three letters, which is what stops the table being mistaken for
    /// the periodic table. The content build rejects anything else.
    /// </summary>
    [Serializable]
    public class ElementJson
    {
        public string id;
        public string name;
        public string symbol;
        public string domain;
        public string color;
    }

    /// <summary>An element and how much of it. JsonUtility cannot read a map.</summary>
    [Serializable]
    public class ElementQuantityJson
    {
        public string element;
        public int quantity;
    }

    /// <summary>A material and how much of it.</summary>
    [Serializable]
    public class MaterialQuantityJson
    {
        public string material;
        public int quantity;
    }

    // ------------------------------------------------------------- materials

    [Serializable]
    public class MaterialJson
    {
        public string id;
        public string name;
        public string description;
        /// <summary>The only biome it can be found in. Enforced at build time.</summary>
        public string biome;
        /// <summary>Exactly two, always.</summary>
        public string[] elements = new string[0];
        public string shape;
        public string color;
    }

    // ------------------------------------------------------------- the world

    [Serializable]
    public class PointJson
    {
        public float x;
        public float y;
    }

    [Serializable]
    public class PaletteJson
    {
        public string ground;
        public string groundAlt;
        public string accent;
        public string fog;
    }

    /// <summary>
    /// A region of the one continuous Coliseum. Not a level: there is no load
    /// between these, and nothing gates on player level.
    /// </summary>
    [Serializable]
    public class BiomeJson
    {
        public string id;
        public string name;
        public string position;
        public PointJson centre;
        public float radius;
        public float distanceFromCentre;
        public string mood;
        public PaletteJson palette;
        public int nodeCount;
        public float respawnSeconds;
        public string[] materials = new string[0];
    }

    [Serializable]
    public class TravelSecondsJson
    {
        public float[] walk = new float[0];
        public float[] sprint = new float[0];
    }

    [Serializable]
    public class ColiseumJson
    {
        public float boundaryRadius;
        public TravelSecondsJson travelSeconds;
    }

    // ------------------------------------------------------------- crafting

    /// <summary>Which gauntlet stat a recipe permanently raises.</summary>
    [Serializable]
    public class CraftEffectJson
    {
        public string stat;
        public float amount;
    }

    [Serializable]
    public class CraftingRecipeJson
    {
        public string id;
        public string name;
        public string description;
        public List<MaterialQuantityJson> cost = new List<MaterialQuantityJson>();
        public CraftEffectJson effect;
    }

    [Serializable]
    public class BaseStatsJson
    {
        public float carryCapacity = 60f;
        public float pullRadius = 600f;
        public float pullSpeed = 1200f;
    }

    /// <summary>Crafting consumes materials and produces permanent upgrades.</summary>
    [Serializable]
    public class CraftingJson
    {
        public BaseStatsJson baseStats = new BaseStatsJson();
        public List<CraftingRecipeJson> recipes = new List<CraftingRecipeJson>();
    }

    // ------------------------------------------------------------- alchemy

    [Serializable]
    public class AbilityEffectJson
    {
        public string kind;
        public float damage;
        public float knockback;
        public float radius;
        public float range;
        public float burnSeconds;
    }

    /// <summary>
    /// Alchemy consumes elements and produces combat abilities - not items.
    /// Locked until Level 2, except the handful handed over at Level 1.
    /// </summary>
    [Serializable]
    public class AlchemyCombinationJson
    {
        public string id;
        public string name;
        public string description;
        public List<ElementQuantityJson> elements = new List<ElementQuantityJson>();
        public bool tutorial;
        public AbilityEffectJson effect;
    }

    // ------------------------------------------------------------- enemies

    /// <summary>
    /// A rendering of hostile code, in one of exactly three tiers. Deliberately
    /// carries no drop table: materials come from the world, and rewarding kills
    /// with material would make fighting a gathering strategy.
    /// </summary>
    [Serializable]
    public class EnemyJson
    {
        public string id;
        public string name;
        public int tier;
        public string represents;
        public string description;
        public string shape;
        public string color;
        public float hp;
        public float damage;
        public float speed;
        public float aggroRadius;
        public float attackRange;
    }

    // ------------------------------------------------------------- waves

    [Serializable]
    public class WavePacingJson
    {
        public int wavesPerBundle = 3;
        public float[] secondsBetweenWaves = new float[0];
        public float[] secondsBetweenBundles = new float[0];
        public float[] secondsToClearWave = new float[0];
    }

    /// <summary>
    /// Timing is scheduled; composition is rolled. A bundle is three waves, the
    /// gap to the next is timed from the END of the previous one, and at most
    /// one full bundle is alive at a time.
    /// </summary>
    [Serializable]
    public class WavesJson
    {
        public string activePacing = "mobile";
        public WavePacingJson canon = new WavePacingJson();
        public WavePacingJson mobile = new WavePacingJson();
        public int maxLiveWaveGroups = 3;
        public bool showEnemiesDuringFirstBundle = true;
    }

    // ------------------------------------------------------------- progression

    /// <summary>XP is novelty, not volume: first-time events only.</summary>
    [Serializable]
    public class XpJson
    {
        public int firstMaterial;
        public int firstCraft;
        public int firstAlchemy;
        public int firstBiome;
        public int clearWave;
    }

    [Serializable]
    public class PlayerJson
    {
        public float moveSpeed = 70f;
        public float sprintSpeed = 84f;
        public float radius = 11f;
        public float pullSeconds = 0.45f;
    }

    [Serializable]
    public class CombatJson
    {
        public float maxHp = 60f;
        public float invulnerableSeconds = 0.7f;
        public float regenPerSecond = 1.5f;
        public float regenDelaySeconds = 6f;
        public float respawnSeconds = 3f;
    }

    [Serializable]
    public class ProgressionJson
    {
        public int alchemyUnlockLevel = 2;
        public int classLevel = 5;
        public XpJson xp = new XpJson();
        public int[] xpTable = new int[0];
        public PlayerJson player = new PlayerJson();
        public CombatJson combat = new CombatJson();
    }

    [Serializable]
    public class TutorialStepJson
    {
        public string id;
        public string title;
        public string hint;
    }
}
