using System;
using System.Collections.Generic;

namespace OrbSystem.ContentModel
{
    /// <summary>
    /// Serializable mirrors of unity/Assets/Resources/maelstrom-content.json.
    ///
    /// That file is GENERATED by tools/build-content.mjs from content/*.json -
    /// the same source the web build uses - so the two runtimes cannot disagree
    /// about what anything is made of. Do not edit it by hand; edit content/ and
    /// re-run `npm run build:content`.
    ///
    /// Shapes here are constrained by JsonUtility: no dictionaries, no nullable
    /// primitives, no top-level arrays. The build step already flattens element
    /// maps into ElementQuantityJson arrays for exactly this reason.
    /// </summary>
    [Serializable]
    public class ContentBundleJson
    {
        public int version;
        public ProgressionJson progression;
        public List<ElementJson> elements = new List<ElementJson>();
        public List<MaterialJson> materials = new List<MaterialJson>();
        public List<TransmutationJson> transmutation = new List<TransmutationJson>();
        public List<AlchemyJson> alchemy = new List<AlchemyJson>();
        public List<ZoneJson> zones = new List<ZoneJson>();
        public List<EnemyJson> enemies = new List<EnemyJson>();
        public List<TutorialStepJson> tutorial = new List<TutorialStepJson>();
    }

    [Serializable]
    public class ProgressionJson
    {
        public int alchemyUnlockLevel = 5;
        public int orbCount = 2;
        public int maxLevel = 25;
        public float decompositionYield = 0.6f;
        public XpJson xp = new XpJson();
        public int[] xpTable = new int[0];
        public CombatJson combat = new CombatJson();
        public PlayerJson player = new PlayerJson();
    }

    [Serializable]
    public class XpJson
    {
        public int gather = 4;
        public int gatherNewMaterial = 30;
        public float repeatTransmuteFactor = 0.2f;
        public float repeatAlchemyFactor = 0.25f;
        public int decompose = 6;
    }

    [Serializable]
    public class ElementJson
    {
        public string id;
        public string name;
        public string description;
        public string color;
        // Periodic-table layout. The alchemy screen is generated from these, so a
        // duplicate symbol or cell is a content error the build already rejects.
        public string symbol;
        public int number;
        public string group;
        public int row;
        public int col;
    }

    [Serializable]
    public class ElementQuantityJson
    {
        public string element;
        public int quantity;
    }

    [Serializable]
    public class MaterialJson
    {
        public string id;
        public string name;
        public string description;
        public List<string> tags = new List<string>();
        public string shape;
        public string color;
        public string source;
        public int tier;
        public int availableAtLevel;
        public List<ElementQuantityJson> composition = new List<ElementQuantityJson>();

        /// <summary>
        /// Weapon damage. JsonUtility has no nullable int, so a non-weapon reads
        /// back as 0; the build refuses to emit a weapon without a damage value,
        /// so 0 here always means "not a weapon" and never "a broken weapon".
        /// </summary>
        public int damage;
    }

    [Serializable]
    public class TransmutationJson
    {
        public string id;
        public string a;
        public string b;
        public string result;
        public int requiredLevel;
        public int xp;
    }

    [Serializable]
    public class AlchemyJson
    {
        public string id;
        public string result;
        public int requiredLevel;
        public int xp;
        public List<ElementQuantityJson> requiredElements = new List<ElementQuantityJson>();
    }

    [Serializable]
    public class ZoneJson
    {
        public string id;
        public string name;
        public string subtitle;
        public string description;
        public int requiredLevel;
        public SizeJson size = new SizeJson();
        public PaletteJson palette = new PaletteJson();
        public int nodeCount;
        public float respawnSeconds;
        public List<SpawnJson> spawns = new List<SpawnJson>();
        public List<string> enemies = new List<string>();
        public int enemyCount;
    }

    [Serializable]
    public class SizeJson
    {
        public float w;
        public float h;
    }

    [Serializable]
    public class PaletteJson
    {
        public string ground;
        public string groundAlt;
        public string accent;
        public string fog;
    }

    [Serializable]
    public class SpawnJson
    {
        public string material;
        public float weight;
    }

    [Serializable]
    public class CombatJson
    {
        public int maxHp = 60;
        public int baseDamage = 3;
        public float attackRange = 52f;
        public float attackCooldown = 0.5f;
        public float attackArc = 1.6f;
        public float knockback = 26f;
        public float invulnerableSeconds = 0.6f;
        public float regenPerSecond = 2.5f;
        public float regenDelaySeconds = 5f;
        public float respawnSeconds = 2.5f;
    }

    [Serializable]
    public class PlayerJson
    {
        public float moveSpeed = 168f;
        public float gatherRadius = 42f;
        public float radius = 13f;
        public float gatherGraceSeconds = 0.45f;
        public float gatherGraceRangeFactor = 2f;
    }

    [Serializable]
    public class EnemyJson
    {
        public string id;
        public string name;
        public string description;
        public string shape;
        public string color;
        public int hp;
        public int damage;
        public float speed;
        public float aggroRadius;
        public float attackRange;
        public float attackCooldown;
        public int xp;
        public List<EnemyDropJson> drops = new List<EnemyDropJson>();
    }

    [Serializable]
    public class EnemyDropJson
    {
        public string material;
        public float chance;
    }

    /// <summary>
    /// One card of the opening guide. The rule that completes each step is code,
    /// keyed by id - see web/src/core/tutorial.ts for the reference implementation.
    /// </summary>
    [Serializable]
    public class TutorialStepJson
    {
        public string id;
        public string title;
        public string hint;
    }
}
