using System;
using System.Collections.Generic;

namespace OrbSystem.ContentModel
{
    /// <summary>
    /// Serializable mirrors of unity/Assets/Resources/maelstrom-content.json.
    ///
    /// That file is GENERATED by tools/build-content.mjs from content/*.json -
    /// the same source the web build uses - so the two runtimes cannot disagree
    /// about what anything is made of. Do not edit it by hand; edit content/ and
    /// re-run `npm run build:content`.
    ///
    /// Shapes here are constrained by JsonUtility: no dictionaries, no nullable
    /// primitives, no top-level arrays. The build step already flattens element
    /// maps into ElementQuantityJson arrays for exactly this reason.
    /// </summary>
    [Serializable]
    public class ContentBundleJson
    {
        public int version;
        public ProgressionJson progression;
        public List<ElementJson> elements = new List<ElementJson>();
        public List<MaterialJson> materials = new List<MaterialJson>();
        public List<TransmutationJson> transmutation = new List<TransmutationJson>();
        public List<AlchemyJson> alchemy = new List<AlchemyJson>();
        public List<ZoneJson> zones = new List<ZoneJson>();
    }

    [Serializable]
    public class ProgressionJson
    {
        public int alchemyUnlockLevel = 5;
        public int orbCount = 2;
        public int maxLevel = 25;
        public float decompositionYield = 0.6f;
        public XpJson xp = new XpJson();
        public int[] xpTable = new int[0];
    }

    [Serializable]
    public class XpJson
    {
        public int gather = 4;
        public int gatherNewMaterial = 30;
        public float repeatTransmuteFactor = 0.2f;
        public float repeatAlchemyFactor = 0.25f;
        public int decompose = 6;
    }

    [Serializable]
    public class ElementJson
    {
        public string id;
        public string name;
        public string description;
        public string color;
    }

    [Serializable]
    public class ElementQuantityJson
    {
        public string element;
        public int quantity;
    }

    [Serializable]
    public class MaterialJson
    {
        public string id;
        public string name;
        public string description;
        public List<string> tags = new List<string>();
        public string shape;
        public string color;
        public string source;
        public int tier;
        public int availableAtLevel;
        public List<ElementQuantityJson> composition = new List<ElementQuantityJson>();
    }

    [Serializable]
    public class TransmutationJson
    {
        public string id;
        public string a;
        public string b;
        public string result;
        public int requiredLevel;
        public int xp;
    }

    [Serializable]
    public class AlchemyJson
    {
        public string id;
        public string result;
        public int requiredLevel;
        public int xp;
        public List<ElementQuantityJson> requiredElements = new List<ElementQuantityJson>();
    }

    [Serializable]
    public class ZoneJson
    {
        public string id;
        public string name;
        public string subtitle;
        public string description;
        public int requiredLevel;
        public SizeJson size = new SizeJson();
        public PaletteJson palette = new PaletteJson();
        public int nodeCount;
        public float respawnSeconds;
        public List<SpawnJson> spawns = new List<SpawnJson>();
    }

    [Serializable]
    public class SizeJson
    {
        public float w;
        public float h;
    }

    [Serializable]
    public class PaletteJson
    {
        public string ground;
        public string groundAlt;
        public string accent;
        public string fog;
    }

    [Serializable]
    public class SpawnJson
    {
        public string material;
        public float weight;
    }
}
