/**
 * The cover art, drawn by the game's own art code.
 *
 * Every mark on this image comes from the build: the character is the real
 * sprite sheet, the materials inside the orb are the real `drawIcon`, and every
 * colour is read out of `content/` - the mountains are the Snowy Mountain's own
 * palette, the ruin is the Data-Center's, the ground is the spawn's, and the
 * orb is the spawn's accent lightened rather than a green picked by eye.
 * Nothing is painted by hand and nothing is generated by an image model, which
 * is the whole claim the project makes about its art; a cover that broke it
 * would be the one piece of art in the repository that was not true.
 *
 * ## The composition
 *
 * Laid out to a brief, back to front:
 *
 * - **The wall**, furthest away and so vast that a mountain range stands in
 *   front of it. Canon's arena is 1.5km across and contains all five regions;
 *   the only honest way to draw that is to put the boundary behind the
 *   landscape rather than around it.
 * - **The mountain range and the abandoned Data-Center**, the two regions the
 *   spawn deliberately withholds - the cold one, and the one you are hiding
 *   from. They are the reason to leave the middle, so they are the horizon.
 * - **The character**, front on, at the bottom.
 * - **The orb**, held in front of them, transparent, with material suspended
 *   inside it. It is drawn after the figure and kept translucent on purpose:
 *   an opaque orb is a ball, and the one thing this object has to communicate
 *   is that it holds what you have gathered.
 *
 * ## Pixel art, and why the backdrop is drawn rather than filtered
 *
 * Everything behind the character is painted into a 128x128 buffer a pixel at a
 * time and scaled up with smoothing off. Running a smooth picture through a
 * pixelate filter would have been a tenth of the work and it produces soft
 * shapes made of squares - the look of a screenshot that has been through
 * something, rather than of art that was authored. Drawn, every edge is a
 * decision: a ridge is a list of integer heights, a snowline is a comparison,
 * and a tower is four pixels wide because five looked wrong.
 *
 * ## Why it is stylised rather than rendered
 *
 * The art this reuses is flat, keylined and bold. An earlier pass staged the
 * cover as a cinematic scene - a lit floor receding to a horizon, creatures at
 * several depths - and flat art in a rendered space reads as stickers on a
 * gradient however carefully it is lit. So this is built the way the art is:
 * separated planes, each a flat value, getting paler and hazier with distance.
 * That is a screen-print's logic rather than a camera's, and it is the one that
 * flatters a keyline.
 *
 * Exposed to the tool as `window.__drawCover`, which is the only reason any of
 * this lives outside `web/src`: it must not ship in the game bundle.
 */
import { drawIcon, withAlpha } from '../../web/src/game/icons';
import sheetUrl from '../../web/src/assets/alchemist.png';

interface Biome {
  id: string;
  palette: { ground: string; groundAlt: string; accent: string; fog: string };
}
interface Material {
  id: string;
  shape: string;
  color: string;
  biome: string;
}
interface Bundle {
  biomes: Biome[];
  materials: Material[];
}

const bundle = (await import('@content/maelstrom-content.json')).default as unknown as Bundle;

const biome = (id: string) => bundle.biomes.find((b) => b.id === id)!;
const material = (id: string) => bundle.materials.find((m) => m.id === id)!;

const SPAWN = biome('plains_forest').palette;
const PEAKS = biome('snowy_mountain').palette;
const RUIN = biome('data_center').palette;

/** Sprite sheet geometry, matching tools/make-sprites.mjs. */
const SPRITE_W = 16;
const SPRITE_H = 24;
/** Row 0 is the `down` facing - the character looking at you. Frame 0 is standing. */
const SPRITE_ROW = 0;
const SPRITE_FRAME = 0;

/** The pull's colour, taken from the ring the game actually draws. */
const PULL = '#9fd8e8';

/** Where the ground meets the far regions. */
const HORIZON = 0.565;

/** The orb's green: the spawn's own accent, saturated out of its olive. */
const GLASS = saturate(SPAWN.accent, 2.1);

/* ------------------------------------------------------------- utilities -- */

function channels(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/** Mix toward white. Used so every derived colour still comes from content/. */
function lighten(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const to = (v: number) => Math.round(v + (255 - v) * k);
  return `rgb(${to(r)}, ${to(g)}, ${to(b)})`;
}

/**
 * Push a colour away from its own grey, keeping its hue.
 *
 * The spawn's accent is an olive - correct for grass, and a muddy thing to make
 * an orb out of. Saturating it rather than picking a brighter green by eye
 * keeps the one rule this file is built on: every colour in the image comes out
 * of content/, and changing the biome's palette changes the cover.
 */
function saturate(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const grey = r * 0.299 + g * 0.587 + b * 0.114;
  const to = (v: number) =>
    Math.max(0, Math.min(255, Math.round(grey + (v - grey) * k)))
      .toString(16)
      .padStart(2, '0');
  // Hex out, not rgb(), so the result can be fed back into lighten/darken.
  return `#${to(r)}${to(g)}${to(b)}`;
}

/** Mix toward black. */
function darken(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const to = (v: number) => Math.round(v * (1 - k));
  return `rgb(${to(r)}, ${to(g)}, ${to(b)})`;
}

/**
 * Deterministic noise, so the cover regenerates byte-identical.
 *
 * A cover that reshuffles every time it is built is a cover nobody can commit,
 * and this one is committed.
 */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

/* -------------------------------------------------------------- backdrop -- */

/**
 * Everything behind the character is drawn as pixel art.
 *
 * Not a filter over a smooth picture - a filter gives you soft shapes made of
 * squares, which is the look of a screenshot that has been through something
 * rather than of art that was authored. This renders the whole backdrop into a
 * 128x128 buffer, one pixel at a time, and scales it up with smoothing off. So
 * every edge is a decision: a ridge is a list of integer heights, a snowline is
 * a comparison, and a tower is four pixels wide because five looked wrong.
 *
 * 128 is chosen against the character. The sprite sheet is 16x24 drawn about
 * 384 tall, which puts a sprite pixel at roughly 16 screen pixels; the backdrop
 * lands on 8. Two to one is a deliberate ratio rather than a coincidence - the
 * figure stays the chunkiest thing in the frame, which is where the eye should
 * go, and the two grids are still in register.
 */
const PX = 128;

/** The horizon, in buffer pixels. */
const PX_HORIZON = Math.round(HORIZON * PX);

/**
 * The palette.
 *
 * Small on purpose. Pixel art reads by value steps rather than by gradients,
 * and every colour added is one more step for the eye to resolve at the size a
 * cover is actually seen. The sky is eight, the rock is four, the snow is
 * three, the ruin is four.
 */
const SKY = [
  '#3b5280',
  '#4a5e8b',
  '#5a6a94',
  '#626a91',
  '#787492',
  '#8e7e91',
  '#a68992',
  '#bd9690',
  '#d0a689',
  '#e0b886',
  '#eecb90',
  '#f8dda6',
  '#fdeec4',
];
const SUN = ['#fffae6', '#ffedbe', '#fcd694'];
const CLOUD = { dark: '#6e6685', mid: '#a08a8c', lit: '#e6b98e', hot: '#fde3b4' };
const ROCK = {
  lit: '#8a7f85',
  mid: PEAKS.ground,
  dark: darken(PEAKS.ground, 0.38),
  far: lighten(PEAKS.groundAlt, 0.16),
  strata: darken(PEAKS.ground, 0.16),
};
const SNOW = {
  /*
   * The lit face is warm and the shadowed face is cold.
   *
   * Snow under a low sun is the clearest case there is: the faces pointing at
   * it take the light's colour and the faces pointing away take the sky's.
   * Drawn from one white with two brightnesses, a range reads as grey card -
   * which is exactly how the first pass came out.
   */
  lit: '#fbe6d2',
  mid: '#d9cfd8',
  dark: darken(PEAKS.accent, 0.42),
};
/** Rust, for a Data-Center that stopped being maintained a long time ago. */
const RUST = { lit: '#8a5a3a', mid: '#5f3d2b', dark: '#2f2529', body: '#3d3338', glass: '#23202b' };
const TREE = { lit: '#2b3d31', dark: '#18231d' };
const FOG = ['#b9adb4', '#8f8694'] as const;

/**
 * A 4x4 ordered dither.
 *
 * The one technique this whole backdrop depends on. A sunset is a gradient and
 * a gradient in eight colours is eight stripes; threshold each pixel against
 * this matrix on the way between two steps and the stripes break up into the
 * speckled transitions that read as pixel-art sky rather than as banding.
 */
const BAYER = [
  [0, 8, 2, 10],
  [12, 4, 14, 6],
  [3, 11, 1, 9],
  [15, 7, 13, 5],
];

function dither(x: number, y: number, frac: number): boolean {
  return (BAYER[y & 3]![x & 3]! + 0.5) / 16 < frac;
}

/** One pixel. */
function px(g: CanvasRenderingContext2D, x: number, y: number, color: string): void {
  if (x < 0 || y < 0 || x >= PX || y >= PX) return;
  g.fillStyle = color;
  g.fillRect(x, y, 1, 1);
}

/** A run of pixels, which is most of what this file draws. */
function row(g: CanvasRenderingContext2D, x0: number, x1: number, y: number, color: string): void {
  if (y < 0 || y >= PX) return;
  const a = Math.max(0, Math.min(x0, x1));
  const b = Math.min(PX - 1, Math.max(x0, x1));
  if (b < a) return;
  g.fillStyle = color;
  g.fillRect(a, y, b - a + 1, 1);
}

function column(g: CanvasRenderingContext2D, x: number, y0: number, y1: number, color: string): void {
  if (x < 0 || x >= PX) return;
  const a = Math.max(0, Math.min(y0, y1));
  const b = Math.min(PX - 1, Math.max(y0, y1));
  if (b < a) return;
  g.fillStyle = color;
  g.fillRect(x, a, 1, b - a + 1);
}

/* ------------------------------------------------------------------ sky -- */

function paintSky(g: CanvasRenderingContext2D): void {
  const last = SKY.length - 1;
  for (let y = 0; y < PX_HORIZON; y++) {
    // Squared, so the warm end of the ramp is compressed into the few rows
    // above the horizon the way a real sunset compresses it.
    const t = Math.pow(y / (PX_HORIZON - 1), 1.12);
    const f = t * last;
    const i = Math.min(last - 1, Math.floor(f));
    const frac = f - i;
    for (let x = 0; x < PX; x++) {
      px(g, x, y, dither(x, y, frac) ? SKY[i + 1]! : SKY[i]!);
    }
  }
}

/**
 * The sun, low and to the right.
 *
 * Its glow is drawn as discrete rings rather than a radial gradient, for the
 * same reason the sky is dithered: a soft falloff sampled onto a 128-pixel grid
 * is a smudge, and a ring of one colour is a sun.
 */
function paintSun(g: CanvasRenderingContext2D): void {
  const sx = 104;
  const sy = 33;

  for (const [r, color, chance] of [
    [20, SKY[8]!, 0.4],
    [14, SKY[9]!, 0.55],
    [10, SUN[2]!, 0.9],
    [7, SUN[1]!, 1],
    [4, SUN[0]!, 1],
  ] as const) {
    for (let y = sy - r; y <= sy + r; y++) {
      for (let x = sx - r; x <= sx + r; x++) {
        const d = Math.hypot(x - sx, (y - sy) * 1.05);
        if (d > r) continue;
        // Ragged edges on the outer rings, so the glow does not read as a
        // series of concentric discs.
        if (chance < 1 && d > r - 3 && !dither(x, y, chance * (1 - (d - (r - 3)) / 3))) continue;
        px(g, x, y, color);
      }
    }
  }

  // The band of light it throws along the horizon.
  for (let y = PX_HORIZON - 12; y < PX_HORIZON; y++) {
    const t = 1 - (PX_HORIZON - y) / 12;
    for (let x = 40; x < PX; x++) {
      const across = Math.min(1, (x - 40) / 70);
      if (dither(x, y, t * across * 0.55)) px(g, x, y, SKY[7]!);
    }
  }
}

/**
 * Cloud banks.
 *
 * Built from rows rather than from a shape: each cloud is a stack of runs whose
 * width comes from a sine, which gives the soft lozenge a cloud has without
 * ever leaving the grid. Three values - a shadowed underside, a body, and one
 * lit row on top facing the sun - is the whole of the shading, and it is enough
 * because the sun is low and to one side.
 */
function paintClouds(g: CanvasRenderingContext2D): void {
  const random = rng(0xc10d5);
  const banks: { x: number; y: number; w: number; h: number; lit: boolean }[] = [];

  for (let i = 0; i < 26; i++) {
    const y = 24 + Math.pow(random(), 0.6) * (PX_HORIZON - 34);
    banks.push({
      x: random() * PX,
      y,
      w: 6 + random() * 26,
      h: 2 + random() * 3,
      // Only the ones near the sun catch the hot edge.
      lit: random() > 0.45,
    });
  }
  banks.sort((a, b) => a.y - b.y);

  for (const bank of banks) {
    const cx = Math.round(bank.x);
    const cy = Math.round(bank.y);
    const h = Math.round(bank.h);
    for (let r = 0; r <= h; r++) {
      const k = r / h;
      const w = Math.round((bank.w / 2) * Math.sin((1 - k * 0.85) * Math.PI * 0.5));
      const y = cy + r;
      const near = Math.max(0, 1 - Math.abs(cx - 104) / 70) * Math.max(0, 1 - Math.abs(cy - 33) / 40);
      const body = r === h ? CLOUD.dark : k > 0.45 ? CLOUD.mid : CLOUD.lit;
      row(g, cx - w, cx + w, y, body);
      if (r === 0 && bank.lit) {
        row(g, cx - w + 1, cx + w - 1, y, near > 0.25 ? CLOUD.hot : CLOUD.lit);
      }
    }
  }
}

/* ----------------------------------------------------------------- wall -- */

/**
 * The boundary, still there and now a long way off.
 *
 * A circular wall seen from inside projects with its top edge lowest on the far
 * side and rising toward both edges of the frame, where it comes closest - so
 * the crest is a shallow valley, not a line. It sits behind the mountains and
 * below the peak, which is the only way to say "this encloses a landscape"
 * rather than "this is a fence".
 */
function paintWall(g: CanvasRenderingContext2D): void {
  const crest = (x: number) => {
    const d = (x / PX - 0.5) * 2;
    return Math.round(54 - 13 * d * d);
  };

  for (let x = 0; x < PX; x++) {
    const top = crest(x);
    const d = Math.abs(x / PX - 0.5) * 2;
    for (let y = top; y < PX_HORIZON; y++) {
      // Haze: the wall fades into the sky it stands against, and more so the
      // further away that part of it is.
      const depth = (y - top) / Math.max(1, PX_HORIZON - top);
      const hazed = dither(x, y, 0.38 - depth * 0.22 - d * 0.12);
      px(g, x, y, hazed ? '#4b566b' : '#3d4859');
    }
    // Ribs, every fourth pixel, deeper toward the near edges.
    if (x % 4 === 0) {
      for (let y = top + 1; y < PX_HORIZON; y++) {
        if (dither(x, y, 0.35 + d * 0.3)) px(g, x, y, '#333d4d');
      }
    }
    // The lit crest.
    px(g, x, top, dither(x, top, 0.9 - d * 0.35) ? '#a8c6cf' : '#7d9aa8');
    px(g, x, top + 1, dither(x, top + 1, 0.45 - d * 0.2) ? '#6d8a99' : '#4b566b');
  }
}

/* ------------------------------------------------------------ mountains -- */

/**
 * A ridge, as an array of one height per column.
 *
 * Everything about the range is decided here and then read back by the painter:
 * where the rock is lit, where the snow starts, where the trees can grow. A
 * ridge drawn straight to the canvas would have to be re-derived for each of
 * those; a ridge held as numbers is queried.
 */
function ridgeline(seed: number, from: number, to: number, peaks: { at: number; top: number }[], base: number): number[] {
  const random = rng(seed);
  const line: number[] = new Array(PX).fill(base);
  for (let x = from; x <= to; x++) {
    let y = base;
    for (const peak of peaks) {
      const d = Math.abs(x - peak.at);
      const reach = 26 + peak.top * 0.35;
      if (d > reach) continue;
      // A peak is two straight faces, not a bell: a curve reads as a hill and
      // the reference is granite.
      y = Math.min(y, peak.top + d * ((base - peak.top) / reach));
    }
    // Break the faces up so they are not two clean diagonals.
    y += Math.round((random() - 0.5) * 2.4);
    line[x] = Math.round(y);
  }
  // One smoothing pass, which keeps the jitter but removes single-pixel spikes.
  const out = line.slice();
  for (let x = from + 1; x < to; x++) {
    out[x] = Math.round((line[x - 1]! + line[x]! * 2 + line[x + 1]!) / 4);
  }
  return out;
}

function paintRange(
  g: CanvasRenderingContext2D,
  line: number[],
  from: number,
  to: number,
  opts: { rock: [string, string]; snowline: number; snow?: [string, string]; base: number },
): void {
  const random = rng(0x5170e + from);
  for (let x = from; x <= to; x++) {
    const y0 = line[x]!;
    const slope = (line[Math.min(to, x + 1)]! - line[Math.max(from, x - 1)]!) / 2;
    // The sun is on the right, so a face descending to the right catches it.
    const lit = slope > 0.15;
    column(g, x, y0, opts.base, lit ? opts.rock[0]! : opts.rock[1]!);

    /*
     * Strata.
     *
     * Without them a face is one flat column and the range reads as cut paper.
     * Bands that follow the ridge rather than the horizon, broken by the same
     * noise that made the ridge, are what turn a silhouette into rock.
     */
    for (let band = 1; band <= 3; band++) {
      const y = y0 + band * 5 + Math.round(Math.sin(x * 0.35 + band) * 2);
      if (y < opts.base && random() > 0.25) {
        px(g, x, y, ROCK.strata);
        if (random() > 0.6) px(g, x, y + 1, opts.rock[1]!);
      }
    }

    if (opts.snow && y0 < opts.snowline) {
      // Deeper snow the higher the ground, with a ragged lower edge so the
      // snowline is not a contour drawn on the hill.
      const depth = Math.round((opts.snowline - y0) * (lit ? 0.62 : 0.4) + random() * 2.2);
      for (let y = y0; y < y0 + depth; y++) {
        px(g, x, y, lit ? opts.snow[0]! : opts.snow[1]!);
      }
      // A hard bright pixel right on the ridge: the light edge is what makes a
      // flat shape read as a solid with a top.
      if (lit) px(g, x, y0, SNOW.lit);
    } else if (lit) {
      px(g, x, y0, opts.rock[0]!);
    }
  }
}

/**
 * Conifers.
 *
 * A tree is six rows of widths 0,0,1,1,2,2 and a one-pixel trunk. The first
 * version scaled the width by height and produced 0,0,1,1 at every size, which
 * is a blob with a point on it; a conifer is only legible at this scale if the
 * steps are authored rather than derived.
 */
function paintTrees(g: CanvasRenderingContext2D, line: number[], from: number, to: number, seed: number, density: number): void {
  const random = rng(seed);
  for (let x = from; x <= to; x++) {
    if (random() > density) continue;
    const base = line[x]! + 1;
    const tall = random() > 0.6;
    const widths = tall ? [0, 0, 1, 1, 1, 2, 2] : [0, 0, 1, 1, 2];
    const shade = random() > 0.45 ? TREE.lit : TREE.dark;
    for (let i = 0; i < widths.length; i++) {
      const y = base - widths.length + i;
      row(g, x - widths[i]!, x + widths[i]!, y, shade);
    }
    px(g, x, base, TREE.dark);
  }
}

/* ----------------------------------------------------------- data-centre -- */

/**
 * The Data-Center, rusted through.
 *
 * Canon's line for the region is "still running, with growth creeping through
 * it", and the earlier pass drew that as a lit skyline - which came out as a
 * city at night rather than as a ruin. Rust reads as abandonment at a glance in
 * a way that a dark window does not, so the towers are iron oxide, their tops
 * are broken rather than flat, and exactly four windows in the whole plant are
 * still lit. That is the "still running" part, and four is enough to be
 * unsettling where forty would be a commute.
 */
function paintRuin(g: CanvasRenderingContext2D, base: number): void {
  const random = rng(0xda7ace);

  /*
   * Shapes, not a skyline.
   *
   * The first version rolled a row of rust-coloured columns and came out as a
   * fence: same width, same colour, same top. A plant reads as a plant because
   * the parts do different jobs - long low halls, a couple of stacks, two
   * cooling towers that are wider at the bottom, and one tower that used to be
   * the tall one. Rust is the accent on a dark body rather than the body
   * itself, which is the difference between corroded steel and timber.
   */
  const halls: { x: number; w: number; h: number }[] = [
    { x: 60, w: 13, h: 7 },
    { x: 75, w: 18, h: 5 },
    { x: 96, w: 11, h: 6 },
    { x: 110, w: 16, h: 8 },
  ];
  const blocks: { x: number; w: number; h: number }[] = [
    { x: 63, w: 5, h: 15 },
    { x: 70, w: 7, h: 22 },
    { x: 84, w: 4, h: 13 },
    { x: 90, w: 6, h: 27 },
    { x: 100, w: 5, h: 17 },
    { x: 112, w: 7, h: 20 },
    { x: 121, w: 5, h: 12 },
  ];

  const solid = (x: number, w: number, h: number, bite: boolean) => {
    for (let cx = x; cx < x + w; cx++) {
      const top = base - h + (bite && random() > 0.7 ? 1 + Math.floor(random() * 3) : 0);
      const face = cx === x + w - 1 ? RUST.mid : cx === x ? RUST.dark : RUST.body;
      column(g, cx, top, base, face);
      // Streaking: rust runs DOWN from the top edge, which is the one detail
      // that says corrosion rather than paint.
      if (random() > 0.55) {
        column(g, cx, top, Math.min(base, top + 2 + Math.floor(random() * 6)), RUST.lit);
      }
      // Dead glass, in bands.
      for (let y = top + 3; y < base - 1; y += 3) {
        if (cx > x && cx < x + w - 1 && random() > 0.45) px(g, cx, y, RUST.glass);
      }
    }
  };

  for (const h of halls) solid(h.x, h.w, h.h, false);
  for (const b of blocks) solid(b.x, b.w, b.h, true);

  // Two cooling towers: wider at the base, open at the top, and the only
  // curved thing in the plant.
  for (const [tx, th] of [
    [79, 19],
    [105, 15],
  ] as const) {
    for (let i = 0; i < th; i++) {
      const k = i / th;
      const w = Math.round(3 + Math.pow(1 - k, 2.2) * 3 + k * 1.4);
      const y = base - i;
      row(g, tx - w, tx + w, y, RUST.body);
      px(g, tx + w, y, RUST.mid);
      px(g, tx - w, y, RUST.dark);
      if (random() > 0.72) px(g, tx - w + 1 + Math.floor(random() * (w * 2 - 1)), y, RUST.lit);
    }
    const lip = Math.round(3 + 1.4);
    row(g, tx - lip, tx + lip, base - th, RUST.dark);
  }

  // The tall stack, bent. A straight one reads as maintained.
  const sx = 93;
  for (let i = 0; i < 30; i++) {
    const drift = i > 20 ? 1 : 0;
    px(g, sx + drift, base - 27 - i, i > 24 ? RUST.dark : RUST.body);
    px(g, sx + 1 + drift, base - 27 - i, RUST.mid);
  }
  row(g, sx - 1, sx + 3, base - 27 - 14, RUST.dark);

  /*
   * Four lights in the whole plant.
   *
   * "Still running" is canon's line for this region, and four is the number
   * that says it: forty is a commute, none is a ruin, four is something that
   * never got switched off.
   */
  for (const [lx, ly, color] of [
    [72, base - 16, RUIN.accent],
    [86, base - 9, material('capacitor_core').color],
    [92, base - 24, RUIN.accent],
    [115, base - 13, material('capacitor_core').color],
  ] as const) {
    px(g, lx, ly, color);
    px(g, lx + 1, ly, withAlpha(color, 0.45));
  }
}

/* ----------------------------------------------------------------- fog -- */

/**
 * The cloud sitting in the valley, which is the reference photograph's whole
 * trick: it separates the ranges from each other and hides where each one
 * meets the ground, so the eye reads depth instead of a stack of cut-outs.
 */
function paintFog(g: CanvasRenderingContext2D, y: number, from: number, to: number, seed: number, strength: number): void {
  const random = rng(seed);
  for (let i = 0; i < 34; i++) {
    const fx = Math.round(from + random() * (to - from));
    const fy = Math.round(y + (random() - 0.5) * 5);
    const w = Math.round(4 + random() * 14);
    const rows = 1 + Math.round(random());
    for (let r = 0; r < rows; r++) {
      let x = fx - w;
      while (x <= fx + w) {
        // Runs with gaps rather than a per-pixel threshold. A dither on a
        // single colour lands on the grid as a checkerboard, and a
        // checkerboard is the one texture that never reads as vapour.
        const run = 1 + Math.round(random() * 3);
        const edge = 1 - Math.abs(x - fx) / (w + 1);
        if (random() < edge * strength) {
          row(g, x, x + run - 1, fy + r, r === 0 && random() > 0.45 ? FOG[0] : FOG[1]);
        }
        x += run + Math.round(random() * 2);
      }
    }
  }
}

/* --------------------------------------------------------------- ground -- */

function paintGround(g: CanvasRenderingContext2D): void {
  /*
   * Ten steps rather than six.
   *
   * The distance a dither has to cover between two colours is what decides
   * whether it reads as shading or as a checkerboard: six steps across
   * fifty-six rows left every transition nine rows deep, which is a chequered
   * field. Ten steps halves that, and the pattern disappears into the grass.
   */
  const ramp = [
    lighten(SPAWN.ground, 0.26),
    lighten(SPAWN.ground, 0.14),
    lighten(SPAWN.groundAlt, 0.04),
    SPAWN.groundAlt,
    darken(SPAWN.groundAlt, 0.12),
    darken(SPAWN.ground, 0.22),
    darken(SPAWN.ground, 0.38),
    darken(SPAWN.ground, 0.54),
    darken(SPAWN.fog, 0.2),
    darken(SPAWN.fog, 0.48),
  ];
  const last = ramp.length - 1;
  for (let y = PX_HORIZON; y < PX; y++) {
    const t = Math.pow((y - PX_HORIZON) / (PX - PX_HORIZON), 0.92);
    const f = t * last;
    const i = Math.min(last - 1, Math.floor(f));
    const frac = f - i;
    for (let x = 0; x < PX; x++) {
      px(g, x, y, dither(x, y, frac) ? ramp[i + 1]! : ramp[i]!);
    }
  }

  // The warm rim the sunset leaves on the near grass, and a scatter of it in
  // the field so the plane is not one flat wash.
  const random = rng(0x6a5510);
  for (let i = 0; i < 110; i++) {
    const y = PX_HORIZON + Math.round(Math.pow(random(), 0.7) * (PX - PX_HORIZON));
    const x = Math.round(random() * PX);
    px(g, x, y, random() > 0.62 ? SPAWN.accent : darken(SPAWN.fog, 0.25));
  }

  /*
   * The near edge of the field catches the low sun.
   *
   * Two rows rather than one, and offset, because a single dithered rule along
   * the horizon is a dashed line - it reads as a border drawn on the picture
   * instead of as light landing on grass.
   */
  for (let r = 0; r < 4; r++) {
    for (let x = 0; x < PX; x++) {
      if (dither(x, r, 0.42 - r * 0.1)) px(g, x, PX_HORIZON + r, lighten(SPAWN.accent, 0.22 - r * 0.05));
    }
  }
}

/**
 * One warm pass over the finished picture.
 *
 * Every plane here was painted with its own palette - the sky's ramp, the
 * range's rock, the ruin's rust - and painted separately they stay separate:
 * correct individually, and together a set of assets rather than a place at a
 * time of day. This lays the sun's colour back over all of them, thickest near
 * the sun and thinning with distance, so the whole frame agrees about where the
 * light is coming from.
 *
 * Dithered rather than blended, because the one rule the backdrop cannot break
 * is that every pixel is one of the palette's colours.
 */
function paintSunlight(g: CanvasRenderingContext2D): void {
  const sx = 104;
  const sy = 33;
  for (let y = 0; y < PX; y++) {
    for (let x = 0; x < PX; x++) {
      const d = Math.hypot(x - sx, (y - sy) * 0.8) / PX;
      const warmth = Math.max(0, 0.42 - d * 0.75);
      if (warmth <= 0) continue;
      if (dither(x + 2, y + 1, warmth)) {
        g.fillStyle = withAlpha(SUN[2]!, 0.16 + warmth * 0.3);
        g.fillRect(x, y, 1, 1);
      }
    }
  }
}

/* ------------------------------------------------------------------------- */

/**
 * The whole backdrop, painted once at 128 and blown up.
 *
 * `imageSmoothingEnabled = false` is the entire difference between pixel art
 * and a blurred small picture, and it has to be set on the context doing the
 * scaling rather than on the one that did the drawing.
 */
function drawBackdrop(ctx: CanvasRenderingContext2D, S: number): void {
  const buf = document.createElement('canvas');
  buf.width = PX;
  buf.height = PX;
  const g = buf.getContext('2d')!;
  g.imageSmoothingEnabled = false;

  paintSky(g);
  paintSun(g);
  paintClouds(g);
  paintWall(g);

  // Far range: high, pale, mostly snow.
  const far = ridgeline(0x51a7e, 0, 78, [
    { at: 20, top: 14 },
    { at: 36, top: 24 },
    { at: 52, top: 30 },
  ], PX_HORIZON - 6);
  paintRange(g, far, 0, 78, {
    rock: [ROCK.far, ROCK.mid],
    snowline: 34,
    snow: [SNOW.lit, SNOW.mid],
    base: PX_HORIZON,
  });

  paintFog(g, PX_HORIZON - 10, 0, PX, 0xf0611, 0.5);

  // The ruin sits in the valley between the two ranges, so the near one crops it.
  paintRuin(g, PX_HORIZON - 3);
  paintFog(g, PX_HORIZON - 6, 52, PX, 0xf0622, 0.38);

  // Near range: lower, darker, and wooded rather than white.
  const near = ridgeline(0x2bb14, 0, 74, [
    { at: 8, top: 44 },
    { at: 30, top: 52 },
    { at: 58, top: 58 },
  ], PX_HORIZON);
  paintRange(g, near, 0, 74, {
    rock: [ROCK.mid, ROCK.dark],
    snowline: 52,
    snow: [SNOW.mid, SNOW.dark],
    base: PX_HORIZON,
  });
  paintTrees(g, near, 2, 72, 0x77ee5, 0.34);

  paintFog(g, PX_HORIZON - 3, 0, PX, 0xf0633, 0.3);
  paintGround(g);
  paintSunlight(g);

  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(buf, 0, 0, PX, PX, 0, 0, S, S);
  ctx.imageSmoothingEnabled = true;
  ctx.restore();
}

/* --------------------------------------------------------------- field -- */

/**
 * Material nodes on the plain, and grass in the very front.
 *
 * Two jobs. The first is that the bottom third was an empty field: a cover with
 * a character standing alone in the middle of one reads as a placeholder,
 * whatever else is in it. The second is that the orb is full of material and
 * nothing else in the image says where any of it came from - these are the same
 * icons, at the sizes the game spawns them, sitting where they grow.
 *
 * Placed rather than scattered: none of them sits on the figure's silhouette,
 * and the nearest are pushed out to the corners so they frame rather than crowd.
 */
const NODES: { id: string; x: number; y: number; scale: number }[] = [
  { id: 'ironvine', x: 0.155, y: 0.655, scale: 0.55 },
  { id: 'loamstone', x: 0.83, y: 0.645, scale: 0.5 },
  { id: 'stormpetal', x: 0.265, y: 0.735, scale: 0.65 },
  { id: 'heartwood_burl', x: 0.79, y: 0.775, scale: 0.8 },
  { id: 'riverglass', x: 0.105, y: 0.855, scale: 1.0 },
  { id: 'ashcap_fungus', x: 0.885, y: 0.915, scale: 1.15 },
];

/**
 * A material icon on the same grid as the backdrop.
 *
 * `drawIcon` is vector, and a smooth icon sitting on pixel-art ground is the
 * one thing that would give the whole trick away. Rendering it small and
 * blowing it up puts it on the grid - and because the icons are bold shapes
 * with a dilated keyline, they survive being reduced to sixteen pixels far
 * better than a shaded illustration would.
 */
function pixelIcon(shape: string, color: string, size: number): HTMLCanvasElement {
  const n = Math.max(8, Math.round(size / 8));
  const c = document.createElement('canvas');
  c.width = n;
  c.height = n;
  const g = c.getContext('2d')!;
  drawIcon(g, shape, color, n);
  return c;
}

function drawField(ctx: CanvasRenderingContext2D, S: number): void {
  for (const node of NODES) {
    const def = material(node.id);
    const x = node.x * S;
    const y = node.y * S;
    const size = S * 0.048 * node.scale;

    // Every node in the game sits in a little light of its own colour, which is
    // how you spot one across a field at walking pace.
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const glow = ctx.createRadialGradient(x, y, 0, x, y, size * 2.1);
    glow.addColorStop(0, withAlpha(def.color, 0.3));
    glow.addColorStop(1, withAlpha(def.color, 0));
    ctx.fillStyle = glow;
    ctx.fillRect(x - size * 2.1, y - size * 2.1, size * 4.2, size * 4.2);
    ctx.restore();

    ctx.save();
    ctx.fillStyle = 'rgba(0,0,0,0.4)';
    ctx.beginPath();
    ctx.ellipse(x, y + size * 0.52, size * 0.42, size * 0.12, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.imageSmoothingEnabled = false;
    const icon = pixelIcon(def.shape, def.color, size);
    ctx.drawImage(icon, 0, 0, icon.width, icon.height, Math.round(x - size / 2), Math.round(y - size / 2), Math.round(size), Math.round(size));
    ctx.imageSmoothingEnabled = true;
    ctx.restore();
  }
}

/**
 * The very front of the picture, in silhouette.
 *
 * Nothing here is identifiable and that is the point: a band of near-black
 * shapes along the bottom edge gives the eye somewhere to start and puts the
 * character behind something, which is the cheapest depth cue there is. Drawn
 * on the backdrop's grid, in whole pixels, so the frame's nearest plane is not
 * the one smooth thing in it.
 */
function drawForeground(ctx: CanvasRenderingContext2D, S: number): void {
  const random = rng(0xf01a6e);
  const unit = S / PX;
  ctx.save();
  ctx.fillStyle = darken(SPAWN.fog, 0.6);
  for (let i = 0; i < 70; i++) {
    // Cleared out of the middle, where the character and the orb are.
    const gx = Math.round(random() * PX);
    if (Math.abs(gx / PX - 0.5) < 0.17) continue;
    const gy = PX - Math.round(Math.pow(random(), 1.8) * 8);
    const h = 3 + Math.round(random() * 8);
    const lean = Math.round((random() - 0.5) * 4);

    // A blade is a column that steps sideways as it rises.
    for (let r = 0; r < h; r++) {
      const k = r / h;
      const x = gx + Math.round(lean * k * k);
      const w = k > 0.65 ? 0 : k > 0.3 ? 0 : 1;
      ctx.fillRect((x - w) * unit, (gy - r) * unit, (w * 2 + 1) * unit, unit);
    }
  }
  ctx.restore();
}

/* -------------------------------------------------------------- the hero -- */

const HERO = { x: 0.5, feet: 0.925, height: 0.355 };
const ORB = { x: 0.5, y: 0.812, r: 0.088 };

function drawHero(ctx: CanvasRenderingContext2D, S: number, sheet: HTMLImageElement): void {
  const h = HERO.height * S;
  const w = (SPRITE_W / SPRITE_H) * h;
  const cx = HERO.x * S;
  const top = HERO.feet * S - h;

  ctx.save();
  ctx.fillStyle = 'rgba(0,0,0,0.45)';
  ctx.beginPath();
  ctx.ellipse(cx, HERO.feet * S, w * 0.46, h * 0.038, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.restore();

  // A pool of dark behind the figure: the hair is near-white and the orb it is
  // holding is lit, so without this the head dissolves at thumbnail size - and
  // thumbnail size is the only size a cover is ever really seen at.
  ctx.save();
  /*
   * The rect has to be bigger than the gradient's own radius.
   *
   * It was h*2 by h*1.7 around a gradient that reaches zero at 0.9h from a
   * centre 0.4h down - so the top of the falloff fell outside the rect and got
   * cut off, leaving a straight horizontal seam across the sky behind the
   * character's head. A soft shape clipped by a hard rectangle is one of the
   * few canvas mistakes that is invisible while you are writing it and obvious
   * the moment you look at the picture.
   */
  const RADIUS = h * 0.9;
  const backing = ctx.createRadialGradient(cx, top + h * 0.4, 0, cx, top + h * 0.4, RADIUS);
  backing.addColorStop(0, 'rgba(5,9,11,0.52)');
  backing.addColorStop(0.6, 'rgba(5,9,11,0.24)');
  backing.addColorStop(1, 'rgba(5,9,11,0)');
  ctx.fillStyle = backing;
  ctx.fillRect(cx - RADIUS, top + h * 0.4 - RADIUS, RADIUS * 2, RADIUS * 2);
  ctx.restore();

  const dx = Math.round(cx - w / 2);
  const dy = Math.round(top);
  const dw = Math.round(w);
  const dh = Math.round(h);

  /*
   * Rim light, and it comes from below.
   *
   * The brightest thing anywhere near this figure is the object it is holding,
   * so the light wraps UP from the orb rather than down from the sky. Getting
   * that backwards is the kind of mistake nothing reports: the picture still
   * looks finished, it just stops agreeing with itself.
   */
  const figure = document.createElement('canvas');
  figure.width = dw;
  figure.height = dh;
  const fg = figure.getContext('2d')!;
  fg.imageSmoothingEnabled = false;
  fg.drawImage(sheet, SPRITE_FRAME * SPRITE_W, SPRITE_ROW * SPRITE_H, SPRITE_W, SPRITE_H, 0, 0, dw, dh);
  fg.globalCompositeOperation = 'source-in';
  fg.fillStyle = lighten(SPAWN.accent, 0.55);
  fg.fillRect(0, 0, dw, dh);

  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  ctx.globalAlpha = 0.28;
  const r = Math.max(1, Math.round(h * 0.011));
  for (const [ox, oy] of [
    [0, r],
    [-r, r * 0.6],
    [r, r * 0.6],
  ]) {
    ctx.drawImage(figure, dx + (ox ?? 0), dy + (oy ?? 0));
  }
  ctx.restore();

  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(sheet, SPRITE_FRAME * SPRITE_W, SPRITE_ROW * SPRITE_H, SPRITE_W, SPRITE_H, dx, dy, dw, dh);
  ctx.imageSmoothingEnabled = true;
  ctx.restore();

  // The gauntlets, lighting up under what they are holding.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (const side of [-1, 1]) {
    const hx = cx + side * w * 0.46;
    const hy = top + h * 0.6;
    const g = ctx.createRadialGradient(hx, hy, 0, hx, hy, h * 0.17);
    g.addColorStop(0, withAlpha(lighten(SPAWN.accent, 0.7), 0.5));
    g.addColorStop(1, withAlpha(SPAWN.accent, 0));
    ctx.fillStyle = g;
    ctx.fillRect(hx - h * 0.17, hy - h * 0.17, h * 0.34, h * 0.34);
  }
  ctx.restore();
}

/* --------------------------------------------------------------- the orb -- */

/**
 * What the gauntlets are holding.
 *
 * Drawn after the figure and kept genuinely transparent - the body behind it
 * stays visible through the glass - because an opaque sphere is a ball, and the
 * one thing this object has to say is that it contains what you have gathered.
 * So it is built in the order glass actually reads: a wash of colour, the
 * contents, an inner shadow that turns a disc into a sphere, a bright edge
 * where the surface turns away, and two speculars.
 *
 * Nine materials from five regions. That is the only claim the orb needs to
 * make - this is a thing that has been somewhere - and it is the game's own
 * `drawIcon` at small scale, on shells, so the near ones are larger and
 * brighter than the far ones.
 */
const CONTENTS: { id: string; a: number; rr: number; depth: number }[] = [
  { id: 'rimeshard', a: 206, rr: 0.5, depth: 1 },
  { id: 'coolant_residue', a: 318, rr: 0.47, depth: 1 },
  { id: 'heartwood_burl', a: 86, rr: 0.53, depth: 0.95 },
  { id: 'stormpetal', a: 152, rr: 0.33, depth: 0.85 },
  { id: 'sunfused_glass', a: 18, rr: 0.36, depth: 0.85 },
  { id: 'riverglass', a: 262, rr: 0.29, depth: 0.7 },
  { id: 'marshgas_bladder', a: 118, rr: 0.18, depth: 0.55 },
  { id: 'loamstone', a: 342, rr: 0.16, depth: 0.5 },
  { id: 'ashcap_fungus', a: 238, rr: 0.63, depth: 0.45 },
];

function drawOrb(ctx: CanvasRenderingContext2D, S: number): void {
  const cx = ORB.x * S;
  const cy = ORB.y * S;
  const R = ORB.r * S;
  const glass = lighten(GLASS, 0.3);

  // The light it throws, which is what makes it a source rather than a decal.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const halo = ctx.createRadialGradient(cx, cy, 0, cx, cy, R * 2.9);
  halo.addColorStop(0, withAlpha(glass, 0.44));
  halo.addColorStop(0.3, withAlpha(GLASS, 0.17));
  halo.addColorStop(1, withAlpha(GLASS, 0));
  ctx.fillStyle = halo;
  ctx.fillRect(cx - R * 3, cy - R * 3, R * 6, R * 6);
  ctx.restore();

  ctx.save();
  ctx.beginPath();
  ctx.arc(cx, cy, R, 0, Math.PI * 2);
  ctx.clip();

  /*
   * The body of the glass.
   *
   * These alphas are the whole brief. They decide whether the character is
   * visible through the orb, and the answer has to be yes - so the fill never
   * goes above a third, and every bright thing inside is drawn additively so it
   * adds light rather than hiding what is behind it.
   */
  /*
   * A wash of dark first, inside the glass.
   *
   * Transparent does not mean the thing behind it comes through unchanged. The
   * character's tunic is the palest part of the sprite and it sits exactly
   * where the orb is, so with only a colour tint over it the orb came out as a
   * bright rectangle with a faint circle drawn round it - correct alpha
   * compositing, wrong picture. This levels what is behind the glass enough for
   * the sphere to be a sphere, while leaving the figure visible through it,
   * which is the whole point of the object.
   */
  ctx.fillStyle = 'rgba(8,18,12,0.46)';
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);

  const body = ctx.createRadialGradient(cx - R * 0.3, cy - R * 0.35, R * 0.08, cx, cy, R);
  body.addColorStop(0, withAlpha(lighten(GLASS, 0.5), 0.34));
  body.addColorStop(0.55, withAlpha(GLASS, 0.32));
  body.addColorStop(1, withAlpha(darken(GLASS, 0.35), 0.38));
  ctx.fillStyle = body;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);

  // Light IN the glass rather than on it. Without this the sphere is a dark
  // disc with bright things inside, which reads as a hole rather than as a
  // volume full of something.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const lit = ctx.createRadialGradient(cx - R * 0.15, cy - R * 0.1, 0, cx, cy, R * 1.05);
  lit.addColorStop(0, withAlpha(lighten(GLASS, 0.45), 0.6));
  lit.addColorStop(0.5, withAlpha(GLASS, 0.34));
  lit.addColorStop(1, withAlpha(GLASS, 0.14));
  ctx.fillStyle = lit;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);
  ctx.restore();

  for (const item of [...CONTENTS].sort((a, b) => a.depth - b.depth)) {
    const def = material(item.id);
    const a = (item.a * Math.PI) / 180;
    const x = cx + Math.cos(a) * item.rr * R;
    const y = cy + Math.sin(a) * item.rr * R;
    const size = R * 0.3 * (0.55 + item.depth * 0.6);

    ctx.save();
    ctx.globalAlpha = 0.6 + item.depth * 0.4;
    ctx.translate(x, y);
    ctx.rotate(Math.sin(item.a) * 0.4);
    ctx.translate(-size / 2, -size / 2);
    drawIcon(ctx, def.shape, def.color, size);
    ctx.restore();

    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const spark = ctx.createRadialGradient(x, y, 0, x, y, size * 1.5);
    spark.addColorStop(0, withAlpha(def.color, 0.26 * item.depth));
    spark.addColorStop(1, withAlpha(def.color, 0));
    ctx.fillStyle = spark;
    ctx.fillRect(x - size * 1.5, y - size * 1.5, size * 3, size * 3);
    ctx.restore();
  }

  // Suspension, so the inside reads as a volume rather than a collage of icons
  // at different sizes.
  const random = rng(0xabcdef);
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (let i = 0; i < 90; i++) {
    const a = random() * Math.PI * 2;
    const rr = Math.sqrt(random()) * R * 0.92;
    ctx.fillStyle = withAlpha(glass, 0.1 + random() * 0.38);
    ctx.beginPath();
    ctx.arc(cx + Math.cos(a) * rr, cy + Math.sin(a) * rr, (S / 1024) * (0.5 + random() * 1.8), 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();

  // The inner shadow that makes a disc into a sphere.
  const inner = ctx.createRadialGradient(cx, cy, R * 0.55, cx, cy, R);
  inner.addColorStop(0, withAlpha('#07120b', 0));
  inner.addColorStop(1, withAlpha('#07120b', 0.34));
  ctx.fillStyle = inner;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);
  ctx.restore();

  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  ctx.lineWidth = R * 0.05;
  const edge = ctx.createLinearGradient(cx - R, cy - R, cx + R, cy + R);
  edge.addColorStop(0, withAlpha(lighten(GLASS, 0.7), 0.62));
  edge.addColorStop(0.45, withAlpha(lighten(GLASS, 0.15), 0.32));
  edge.addColorStop(1, withAlpha(lighten(GLASS, 0.55), 0.75));
  ctx.strokeStyle = edge;
  ctx.beginPath();
  ctx.arc(cx, cy, R * 0.975, 0, Math.PI * 2);
  ctx.stroke();

  // One specular upper left, one bounce lower right. Two is the difference
  // between glass and a coloured circle; three is a bauble.
  ctx.fillStyle = withAlpha('#ffffff', 0.4);
  ctx.beginPath();
  ctx.ellipse(cx - R * 0.42, cy - R * 0.46, R * 0.26, R * 0.15, -0.6, 0, Math.PI * 2);
  ctx.fill();

  const bounce = ctx.createRadialGradient(cx + R * 0.38, cy + R * 0.5, 0, cx + R * 0.38, cy + R * 0.5, R * 0.34);
  bounce.addColorStop(0, withAlpha(lighten(GLASS, 0.7), 0.32));
  bounce.addColorStop(1, withAlpha(GLASS, 0));
  ctx.fillStyle = bounce;
  ctx.fillRect(cx, cy, R, R);
  ctx.restore();
}

/* ------------------------------------------------------------ atmosphere -- */

function drawAir(ctx: CanvasRenderingContext2D, S: number): void {
  const random = rng(0xa11ce);
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (let i = 0; i < 130; i++) {
    const x = random() * S;
    const y = S * 0.3 + random() * S * 0.7;
    // Thickest near the orb, which is where the light is.
    const d = Math.hypot(x - ORB.x * S, y - ORB.y * S) / S;
    if (random() < d * 1.6) continue;
    ctx.fillStyle = withAlpha(random() > 0.4 ? lighten(SPAWN.accent, 0.5) : '#ffffff', 0.12 + random() * 0.3);
    ctx.beginPath();
    ctx.arc(x, y, (0.5 + random() * 1.5) * (S / 1024), 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();

  const v = ctx.createRadialGradient(S * 0.5, S * 0.58, S * 0.26, S * 0.5, S * 0.58, S * 0.88);
  v.addColorStop(0, 'rgba(0,0,0,0)');
  v.addColorStop(0.6, 'rgba(2,6,8,0.24)');
  v.addColorStop(1, 'rgba(2,6,8,0.7)');
  ctx.fillStyle = v;
  ctx.fillRect(0, 0, S, S);
}

/* ------------------------------------------------------------------ type -- */

/** Letterspacing by hand: canvas has no tracking, and a title needs it. */
function tracked(
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  y: number,
  tracking: number,
): void {
  const widths = [...text].map((ch) => ctx.measureText(ch).width);
  const total = widths.reduce((a, b) => a + b, 0) + tracking * (text.length - 1);
  let x = cx - total / 2;
  for (let i = 0; i < text.length; i++) {
    ctx.fillText(text[i] ?? '', x, y);
    x += (widths[i] ?? 0) + tracking;
  }
}

/**
 * The name, across the top.
 *
 * The plate is a gradient rather than a bar: the sky behind the title is
 * already the darkest part of the image, so all it has to do is keep the
 * letterforms off the wall's lit crest, which runs directly under them.
 */
function drawTitle(ctx: CanvasRenderingContext2D, S: number): void {
  const cx = S / 2;

  const plate = ctx.createLinearGradient(0, 0, 0, S * 0.27);
  plate.addColorStop(0, 'rgba(3,6,11,0.82)');
  plate.addColorStop(0.5, 'rgba(3,6,11,0.46)');
  plate.addColorStop(1, 'rgba(3,6,11,0)');
  ctx.fillStyle = plate;
  ctx.fillRect(0, 0, S, S * 0.27);

  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';

  ctx.fillStyle = withAlpha(PULL, 0.78);
  ctx.font = `600 ${S * 0.026}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'PROJECT', cx, S * 0.077, S * 0.023);

  ctx.fillStyle = '#f4f8fc';
  ctx.font = `700 ${S * 0.086}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'MAELSTROM', cx, S * 0.155, S * 0.0125);
}

/* ------------------------------------------------------------------------- */

export async function drawCover(canvas: HTMLCanvasElement, size: number, withTitle: boolean): Promise<void> {
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('no 2d context for the cover');

  const sheet = new Image();
  await new Promise<void>((done, fail) => {
    sheet.onload = () => done();
    sheet.onerror = () => fail(new Error('sprite sheet failed to load'));
    sheet.src = sheetUrl;
  });

  drawBackdrop(ctx, size);
  drawField(ctx, size);
  drawHero(ctx, size, sheet);
  drawOrb(ctx, size);
  drawForeground(ctx, size);
  drawAir(ctx, size);
  if (withTitle) drawTitle(ctx, size);
}

declare global {
  interface Window {
    __drawCover: typeof drawCover;
  }
}

window.__drawCover = drawCover;
