/**
 * The cover art, drawn by the game's own art code.
 *
 * Every mark on this image comes from the build: the character is the real
 * sprite sheet, the materials inside the orb are the real `drawIcon`, and every
 * colour is read out of `content/` - the mountains are the Snowy Mountain's own
 * palette, the ruin is the Data-Center's, the ground is the spawn's, and the
 * orb is the spawn's accent lightened rather than a green picked by eye.
 * Nothing is painted by hand and nothing is generated by an image model, which
 * is the whole claim the project makes about its art; a cover that broke it
 * would be the one piece of art in the repository that was not true.
 *
 * ## The composition
 *
 * Laid out to a brief, back to front:
 *
 * - **The wall**, furthest away and so vast that a mountain range stands in
 *   front of it. Canon's arena is 1.5km across and contains all five regions;
 *   the only honest way to draw that is to put the boundary behind the
 *   landscape rather than around it.
 * - **The mountain range and the abandoned Data-Center**, the two regions the
 *   spawn deliberately withholds - the cold one, and the one you are hiding
 *   from. They are the reason to leave the middle, so they are the horizon.
 * - **The character**, front on, at the bottom.
 * - **The orb**, held in front of them, transparent, with material suspended
 *   inside it. It is drawn after the figure and kept translucent on purpose:
 *   an opaque orb is a ball, and the one thing this object has to communicate
 *   is that it holds what you have gathered.
 *
 * ## Why it is stylised rather than rendered
 *
 * The art this reuses is flat, keylined and bold. An earlier pass staged the
 * cover as a cinematic scene - a lit floor receding to a horizon, creatures at
 * several depths - and flat art in a rendered space reads as stickers on a
 * gradient however carefully it is lit. So this is built the way the art is:
 * separated planes, each a flat value, getting paler and hazier with distance.
 * That is a screen-print's logic rather than a camera's, and it is the one that
 * flatters a keyline.
 *
 * Exposed to the tool as `window.__drawCover`, which is the only reason any of
 * this lives outside `web/src`: it must not ship in the game bundle.
 */
import { drawIcon, withAlpha } from '../../web/src/game/icons';
import sheetUrl from '../../web/src/assets/alchemist.png';

interface Biome {
  id: string;
  palette: { ground: string; groundAlt: string; accent: string; fog: string };
}
interface Material {
  id: string;
  shape: string;
  color: string;
  biome: string;
}
interface Bundle {
  biomes: Biome[];
  materials: Material[];
}

const bundle = (await import('@content/maelstrom-content.json')).default as unknown as Bundle;

const biome = (id: string) => bundle.biomes.find((b) => b.id === id)!;
const material = (id: string) => bundle.materials.find((m) => m.id === id)!;

const SPAWN = biome('plains_forest').palette;
const PEAKS = biome('snowy_mountain').palette;
const RUIN = biome('data_center').palette;

/** Sprite sheet geometry, matching tools/make-sprites.mjs. */
const SPRITE_W = 16;
const SPRITE_H = 24;
/** Row 0 is the `down` facing - the character looking at you. Frame 0 is standing. */
const SPRITE_ROW = 0;
const SPRITE_FRAME = 0;

/** The pull's colour, taken from the ring the game actually draws. */
const PULL = '#9fd8e8';

/** Where the ground meets the far regions. */
const HORIZON = 0.565;

/** The orb's green: the spawn's own accent, saturated out of its olive. */
const GLASS = saturate(SPAWN.accent, 2.1);

/* ------------------------------------------------------------- utilities -- */

function channels(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/** Mix toward white. Used so every derived colour still comes from content/. */
function lighten(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const to = (v: number) => Math.round(v + (255 - v) * k);
  return `rgb(${to(r)}, ${to(g)}, ${to(b)})`;
}

/**
 * Push a colour away from its own grey, keeping its hue.
 *
 * The spawn's accent is an olive - correct for grass, and a muddy thing to make
 * an orb out of. Saturating it rather than picking a brighter green by eye
 * keeps the one rule this file is built on: every colour in the image comes out
 * of content/, and changing the biome's palette changes the cover.
 */
function saturate(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const grey = r * 0.299 + g * 0.587 + b * 0.114;
  const to = (v: number) =>
    Math.max(0, Math.min(255, Math.round(grey + (v - grey) * k)))
      .toString(16)
      .padStart(2, '0');
  // Hex out, not rgb(), so the result can be fed back into lighten/darken.
  return `#${to(r)}${to(g)}${to(b)}`;
}

/** Mix toward black. */
function darken(hex: string, k: number): string {
  const [r, g, b] = channels(hex);
  const to = (v: number) => Math.round(v * (1 - k));
  return `rgb(${to(r)}, ${to(g)}, ${to(b)})`;
}

/**
 * Deterministic noise, so the cover regenerates byte-identical.
 *
 * A cover that reshuffles every time it is built is a cover nobody can commit,
 * and this one is committed.
 */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

/* ------------------------------------------------------------------ sky -- */

function drawSky(ctx: CanvasRenderingContext2D, S: number): void {
  const sky = ctx.createLinearGradient(0, 0, 0, S * HORIZON);
  sky.addColorStop(0, '#070c15');
  sky.addColorStop(0.45, '#101b28');
  sky.addColorStop(0.82, '#21333e');
  sky.addColorStop(1, '#324a52');
  ctx.fillStyle = sky;
  ctx.fillRect(0, 0, S, S * HORIZON + 2);

  /*
   * The maelstrom, faint and high.
   *
   * The brief did not ask for it and it is deliberately almost not there: the
   * subject here is the place and the person, and a storm drawn to compete
   * would take the image off them. But a cover called Project Maelstrom with no
   * maelstrom anywhere in it has quietly changed the subject, so it sits in the
   * sky where weather goes.
   */
  const cx = S * 0.5;
  const cy = S * 0.205;
  const TURNS = 2.6;
  const R_MIN = 0.06;
  const R_MAX = 0.62;
  const k = Math.log(R_MAX / R_MIN) / (TURNS * Math.PI * 2);

  ctx.save();
  ctx.translate(cx, cy);
  ctx.scale(1, 0.3);
  ctx.globalCompositeOperation = 'lighter';
  ctx.lineCap = 'round';
  for (let arm = 0; arm < 5; arm++) {
    const offset = (arm / 5) * Math.PI * 2;
    const at = (t: number) => {
      const theta = t * TURNS * Math.PI * 2;
      const r = R_MAX * Math.exp(-k * theta);
      return { x: Math.cos(theta + offset) * r * S, y: Math.sin(theta + offset) * r * S };
    };
    const STEPS = 240;
    for (let i = 0; i < STEPS; i++) {
      const a = at(i / STEPS);
      const b = at((i + 1) / STEPS);
      const fade = Math.pow(i / STEPS, 1.6);
      ctx.strokeStyle = withAlpha(PULL, 0.06 * (fade * 0.9 + 0.1));
      ctx.lineWidth = S * 0.006 * (0.3 + fade);
      ctx.beginPath();
      ctx.moveTo(a.x, a.y);
      ctx.lineTo(b.x, b.y);
      ctx.stroke();
    }
  }
  ctx.restore();

  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const eye = ctx.createRadialGradient(cx, cy, 0, cx, cy, S * 0.17);
  eye.addColorStop(0, withAlpha(PULL, 0.17));
  eye.addColorStop(0.22, withAlpha(PULL, 0.06));
  eye.addColorStop(1, withAlpha(PULL, 0));
  ctx.fillStyle = eye;
  ctx.fillRect(cx - S * 0.22, cy - S * 0.22, S * 0.44, S * 0.44);
  ctx.restore();
}

/* ----------------------------------------------------------------- wall -- */

/**
 * The boundary of the Coliseum, from inside it.
 *
 * The curve is not decoration. A circular wall of constant height, seen from
 * inside, projects with its top edge LOWEST on the far side and rising toward
 * both edges of the frame, where the wall comes closest to you. Drawn straight
 * it is a fence across a field; drawn as a shallow valley it reads as being
 * surrounded, which is the fact canon is most insistent about.
 *
 * It is one of the palest things in the image rather than the darkest. In a
 * flat, layered picture distance is carried by haze, and this is the furthest
 * plane there is - so it sits close to the colour of the sky it stands against,
 * and only its lit crest says where it ends.
 */
function drawWall(ctx: CanvasRenderingContext2D, S: number): void {
  const far = S * 0.285;
  const near = S * 0.165;
  const top = (x: number) => {
    const d = (x / S - 0.5) * 2;
    return far - (far - near) * d * d;
  };

  ctx.save();
  ctx.beginPath();
  ctx.moveTo(0, top(0));
  for (let x = 0; x <= S; x += S / 160) ctx.lineTo(x, top(x));
  ctx.lineTo(S, S * HORIZON);
  ctx.lineTo(0, S * HORIZON);
  ctx.closePath();

  const face = ctx.createLinearGradient(0, near, 0, S * HORIZON);
  face.addColorStop(0, '#3a505f');
  face.addColorStop(0.5, '#334858');
  face.addColorStop(1, '#2b3f50');
  ctx.fillStyle = face;
  ctx.fill();

  // Buttresses. The wall needs a rhythm or it is a bank of fog; they deepen
  // toward the edges, which is the part of it that is nearest.
  ctx.clip();
  for (let i = 0; i <= 88; i++) {
    const x = (i / 88) * S;
    const d = Math.abs(x / S - 0.5) * 2;
    ctx.fillStyle = withAlpha('#0b1622', 0.05 + d * 0.17);
    ctx.fillRect(x - S * 0.004, top(x), S * 0.008, S);
  }

  // Two string courses, which is the cheapest way to say "built".
  for (const t of [0.3, 0.58]) {
    ctx.fillStyle = withAlpha('#0b1622', 0.13);
    ctx.beginPath();
    ctx.moveTo(0, top(0) + (S * HORIZON - top(0)) * t);
    for (let x = 0; x <= S; x += S / 160) {
      ctx.lineTo(x, top(x) + (S * HORIZON - top(x)) * t);
    }
    for (let x = S; x >= 0; x -= S / 160) {
      ctx.lineTo(x, top(x) + (S * HORIZON - top(x)) * t + S * 0.005);
    }
    ctx.closePath();
    ctx.fill();
  }
  ctx.restore();

  // The lit crest.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  ctx.lineWidth = S * 0.0026;
  ctx.beginPath();
  ctx.moveTo(0, top(0));
  for (let x = 0; x <= S; x += S / 160) ctx.lineTo(x, top(x));
  const rim = ctx.createLinearGradient(0, 0, S, 0);
  rim.addColorStop(0, withAlpha(PULL, 0.18));
  rim.addColorStop(0.5, withAlpha(PULL, 0.44));
  rim.addColorStop(1, withAlpha(PULL, 0.18));
  ctx.strokeStyle = rim;
  ctx.stroke();
  ctx.restore();
}

/* ------------------------------------------------------------ mountains -- */

/**
 * The Snowy Mountain, in two ranges.
 *
 * Two, so the plane has a depth of its own: the far one paler and lower, the
 * near one darker with the caps actually lit. Peaks come from a seeded walk
 * rather than being placed, because a hand-placed range at this width either
 * repeats or wanders, and both read as a texture rather than a horizon.
 */
function range(
  ctx: CanvasRenderingContext2D,
  opts: {
    seed: number;
    from: number;
    to: number;
    base: number;
    high: number;
    low: number;
    fill: string;
    snow?: string;
    step: number;
  },
): void {
  const random = rng(opts.seed);
  const pts: { x: number; y: number }[] = [];
  let x = opts.from;
  let up = true;
  while (x < opts.to) {
    const y = up
      ? opts.high + random() * (opts.low - opts.high) * 0.55
      : opts.low - random() * (opts.low - opts.high) * 0.28;
    pts.push({ x, y });
    x += opts.step * (0.55 + random() * 0.9);
    up = !up;
  }
  pts.push({ x: opts.to, y: opts.low });

  ctx.save();
  ctx.beginPath();
  ctx.moveTo(opts.from, opts.base);
  for (const p of pts) ctx.lineTo(p.x, p.y);
  ctx.lineTo(opts.to, opts.base);
  ctx.closePath();
  ctx.fillStyle = opts.fill;
  ctx.fill();

  /*
   * Snow on the peaks, as a flat wedge rather than a fade.
   *
   * A gradient here reads as mist sitting on a hill; a hard edge reads as snow
   * on rock, which is the same reason the material icons in this project have
   * a keyline instead of soft shading.
   */
  if (opts.snow) {
    ctx.clip();
    for (let i = 1; i < pts.length - 1; i++) {
      const p = pts[i]!;
      const prev = pts[i - 1]!;
      const next = pts[i + 1]!;
      if (!(p.y < prev.y && p.y < next.y)) continue;
      const drop = Math.min(prev.y, next.y) - p.y;
      const cap = p.y + drop * (0.3 + (i % 3) * 0.07);
      ctx.fillStyle = opts.snow;
      ctx.beginPath();
      ctx.moveTo(p.x, p.y);
      ctx.lineTo(p.x - (p.x - prev.x) * ((cap - p.y) / (prev.y - p.y)), cap);
      ctx.lineTo(p.x + (next.x - p.x) * ((cap - p.y) / (next.y - p.y)), cap);
      ctx.closePath();
      ctx.fill();
    }
  }
  ctx.restore();
}

function drawMountains(ctx: CanvasRenderingContext2D, S: number): void {
  range(ctx, {
    seed: 0x51a7e,
    from: -S * 0.05,
    to: S * 0.66,
    base: S * HORIZON,
    high: S * 0.325,
    low: S * 0.5,
    fill: lighten(PEAKS.ground, 0.14),
    step: S * 0.08,
  });
  range(ctx, {
    seed: 0x2bb14,
    from: -S * 0.05,
    to: S * 0.54,
    base: S * HORIZON,
    high: S * 0.375,
    low: S * 0.535,
    fill: darken(PEAKS.ground, 0.18),
    snow: withAlpha(PEAKS.accent, 0.6),
    step: S * 0.095,
  });
  /*
   * A third range, nearest and darkest.
   *
   * Two ranges came out as two grey cards leaning on each other - the eye reads
   * a plane as flat until something in front of it is a different value. The
   * near one is low and dark enough to be a foothill rather than a peak, which
   * is what gives the other two somewhere to be.
   */
  range(ctx, {
    seed: 0x7c0a1,
    from: -S * 0.05,
    to: S * 0.46,
    base: S * HORIZON,
    high: S * 0.462,
    low: S * 0.552,
    fill: darken(PEAKS.ground, 0.52),
    step: S * 0.07,
  });
}

/* ----------------------------------------------------------- data-centre -- */

/**
 * The Data-Center, abandoned and still running.
 *
 * Canon's line for the region is "neon light and coolant fog, still running,
 * with growth creeping through it", so the silhouette is a block plant with a
 * handful of windows left on and two stacks venting - lit, but nobody home.
 * Most windows are dark deliberately: a fully lit block is an office at night.
 * The lights are the region's own accent, the same cyan the coolant material is
 * drawn in, so the horizon and the thing in the orb rhyme.
 */
function drawRuin(ctx: CanvasRenderingContext2D, S: number): void {
  const base = S * HORIZON;
  const random = rng(0xda7ace);

  const blocks: { x: number; w: number; h: number; lean: number }[] = [
    { x: 0.6, w: 0.07, h: 0.062, lean: 0 },
    { x: 0.663, w: 0.105, h: 0.118, lean: 0 },
    { x: 0.762, w: 0.052, h: 0.168, lean: -0.011 },
    { x: 0.808, w: 0.125, h: 0.095, lean: 0 },
    { x: 0.925, w: 0.082, h: 0.138, lean: 0.007 },
    { x: 1.0, w: 0.08, h: 0.076, lean: 0 },
  ];

  ctx.save();
  for (const b of blocks) {
    const x = b.x * S;
    const w = b.w * S;
    const h = b.h * S;
    const lean = b.lean * S;

    ctx.fillStyle = darken(RUIN.ground, 0.12);
    ctx.beginPath();
    ctx.moveTo(x, base);
    ctx.lineTo(x + lean, base - h);
    ctx.lineTo(x + w + lean, base - h);
    ctx.lineTo(x + w, base);
    ctx.closePath();
    ctx.fill();

    // The lit edge, on the side the sky is brightest.
    ctx.fillStyle = withAlpha(lighten(RUIN.accent, 0.1), 0.18);
    ctx.fillRect(x + lean, base - h, Math.max(1, S * 0.0035), h);

    const cols = Math.max(2, Math.round(b.w * 26));
    const rows = Math.max(3, Math.round(b.h * 26));
    for (let cx = 0; cx < cols; cx++) {
      for (let cy = 0; cy < rows; cy++) {
        if (random() > 0.2) continue;
        const wx = x + lean * (1 - cy / rows) + (w * (cx + 0.3)) / cols;
        const wy = base - h + (h * (cy + 0.35)) / rows;
        ctx.fillStyle = withAlpha(
          random() > 0.72 ? RUIN.accent : material('capacitor_core').color,
          0.3 + random() * 0.5,
        );
        ctx.fillRect(wx, wy, (w / cols) * 0.42, (h / rows) * 0.34);
      }
    }
  }

  // Two stacks, and what is coming out of them.
  for (const [sx, sh] of [
    [0.718, 0.215],
    [0.888, 0.182],
  ] as const) {
    const x = sx * S;
    const h = sh * S;
    const w = S * 0.019;
    ctx.fillStyle = darken(RUIN.groundAlt, 0.2);
    ctx.fillRect(x, base - h, w, h);
    ctx.fillStyle = withAlpha(RUIN.accent, 0.14);
    ctx.fillRect(x, base - h, Math.max(1, S * 0.003), h);

    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const vent = ctx.createLinearGradient(0, base - h, 0, base - h - S * 0.12);
    vent.addColorStop(0, withAlpha(RUIN.accent, 0.17));
    vent.addColorStop(1, withAlpha(RUIN.accent, 0));
    ctx.fillStyle = vent;
    ctx.fillRect(x - w, base - h - S * 0.12, w * 3, S * 0.12);
    ctx.restore();
  }
  ctx.restore();

  // The glow the place sits in.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const halo = ctx.createRadialGradient(S * 0.8, base - S * 0.03, 0, S * 0.8, base - S * 0.03, S * 0.32);
  halo.addColorStop(0, withAlpha(RUIN.accent, 0.12));
  halo.addColorStop(1, withAlpha(RUIN.accent, 0));
  ctx.fillStyle = halo;
  ctx.fillRect(0, 0, S, base + S * 0.03);
  ctx.restore();
}

/* --------------------------------------------------------------- ground -- */

function drawGround(ctx: CanvasRenderingContext2D, S: number): void {
  const h = S * HORIZON;

  // The mist the far plane stands in. It is what turns three flat shapes into
  // three distances, and it is the whole of the atmospheric perspective here.
  const mist = ctx.createLinearGradient(0, h - S * 0.075, 0, h + S * 0.03);
  mist.addColorStop(0, withAlpha('#52707c', 0));
  mist.addColorStop(0.6, withAlpha('#52707c', 0.55));
  mist.addColorStop(1, withAlpha('#3f5b66', 0));
  ctx.fillStyle = mist;
  ctx.fillRect(0, h - S * 0.075, S, S * 0.105);

  const ground = ctx.createLinearGradient(0, h, 0, S);
  ground.addColorStop(0, lighten(SPAWN.ground, 0.1));
  ground.addColorStop(0.16, darken(SPAWN.groundAlt, 0.18));
  ground.addColorStop(0.62, darken(SPAWN.ground, 0.58));
  ground.addColorStop(1, darken(SPAWN.fog, 0.45));
  ctx.fillStyle = ground;
  ctx.fillRect(0, h, S, S - h);

  // Bands thinning toward the horizon, which is the whole of the projection in
  // this image: at cover size a real camera and a power curve are the same
  // picture, and one of them is a line of code.
  const BANDS = 22;
  for (let i = 0; i < BANDS; i++) {
    const t0 = Math.pow(i / BANDS, 2.3);
    const t1 = Math.pow((i + 1) / BANDS, 2.3);
    ctx.fillStyle = withAlpha(i % 2 ? SPAWN.accent : SPAWN.fog, 0.018 * (1 - t0 * 0.8));
    ctx.fillRect(0, h + (S - h) * t0, S, (S - h) * (t1 - t0));
  }

  const random = rng(0x5eed10);
  for (let i = 0; i < 260; i++) {
    const t = Math.pow(random(), 0.5);
    const y = h + (S - h) * t;
    const x = random() * S;
    const r = (0.5 + random() * 2) * (S / 1024) * (0.3 + t * 2.6);
    ctx.fillStyle = withAlpha(random() > 0.6 ? SPAWN.accent : SPAWN.groundAlt, 0.1 + random() * 0.2);
    ctx.beginPath();
    ctx.ellipse(x, y, r * 2.4, r, 0, 0, Math.PI * 2);
    ctx.fill();
  }
}

/**
 * Material nodes on the plain, and grass in the very front.
 *
 * Two jobs. The first is that the bottom third was an empty green field: a
 * cover with a character standing alone in the middle of one reads as a
 * placeholder, whatever else is in it. The second is that the orb is full of
 * material and nothing in the image says where any of it came from - these are
 * the same icons, at the same sizes the game spawns them, sitting where they
 * grow. The spawn's own three, because that is the region the ground is.
 *
 * Placed rather than scattered: none of them sits on the figure's silhouette,
 * and the two nearest are pushed out to the corners so they frame rather than
 * crowd.
 */
const NODES: { id: string; x: number; y: number; scale: number }[] = [
  { id: 'ironvine', x: 0.155, y: 0.655, scale: 0.55 },
  { id: 'loamstone', x: 0.83, y: 0.645, scale: 0.5 },
  { id: 'stormpetal', x: 0.265, y: 0.735, scale: 0.65 },
  { id: 'heartwood_burl', x: 0.79, y: 0.775, scale: 0.8 },
  { id: 'riverglass', x: 0.105, y: 0.855, scale: 1.0 },
  { id: 'ashcap_fungus', x: 0.885, y: 0.915, scale: 1.15 },
];

function drawField(ctx: CanvasRenderingContext2D, S: number): void {
  for (const node of NODES) {
    const def = material(node.id);
    const x = node.x * S;
    const y = node.y * S;
    const size = S * 0.048 * node.scale;

    // Every node in the game sits in a little light of its own colour, which is
    // how you spot one across a field at walking pace.
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const glow = ctx.createRadialGradient(x, y, 0, x, y, size * 2.1);
    glow.addColorStop(0, withAlpha(def.color, 0.34));
    glow.addColorStop(1, withAlpha(def.color, 0));
    ctx.fillStyle = glow;
    ctx.fillRect(x - size * 2.1, y - size * 2.1, size * 4.2, size * 4.2);
    ctx.restore();

    ctx.save();
    ctx.fillStyle = 'rgba(0,0,0,0.4)';
    ctx.beginPath();
    ctx.ellipse(x, y + size * 0.52, size * 0.42, size * 0.12, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.translate(x - size / 2, y - size / 2);
    drawIcon(ctx, def.shape, def.color, size);
    ctx.restore();
  }
}

/**
 * The very front of the picture, in silhouette.
 *
 * Nothing here is identifiable and that is the point: a band of near-black
 * shapes along the bottom edge gives the eye somewhere to start and puts the
 * character behind something, which is the cheapest depth cue there is. They
 * are drawn after everything except the air, so they crop the frame rather than
 * sit in the scene.
 */
function drawForeground(ctx: CanvasRenderingContext2D, S: number): void {
  const random = rng(0xf01a6e);
  ctx.save();
  ctx.fillStyle = darken(SPAWN.fog, 0.55);
  for (let i = 0; i < 64; i++) {
    // Cleared out of the middle, where the character and the orb are.
    const x = random() * S;
    if (Math.abs(x / S - 0.5) < 0.17) continue;
    const lift = Math.pow(random(), 1.8);
    const y = S * (1.01 - lift * 0.075);
    const h = S * (0.022 + random() * 0.048);
    const w = S * (0.007 + random() * 0.012);
    const lean = (random() - 0.5) * S * 0.045;

    ctx.beginPath();
    ctx.moveTo(x - w, y);
    ctx.quadraticCurveTo(x - w * 0.4 + lean * 0.5, y - h * 0.6, x + lean, y - h);
    ctx.quadraticCurveTo(x + w * 0.4 + lean * 0.5, y - h * 0.6, x + w, y);
    ctx.closePath();
    ctx.fill();
  }
  ctx.restore();
}

/* -------------------------------------------------------------- the hero -- */

const HERO = { x: 0.5, feet: 0.925, height: 0.355 };
const ORB = { x: 0.5, y: 0.812, r: 0.088 };

function drawHero(ctx: CanvasRenderingContext2D, S: number, sheet: HTMLImageElement): void {
  const h = HERO.height * S;
  const w = (SPRITE_W / SPRITE_H) * h;
  const cx = HERO.x * S;
  const top = HERO.feet * S - h;

  ctx.save();
  ctx.fillStyle = 'rgba(0,0,0,0.45)';
  ctx.beginPath();
  ctx.ellipse(cx, HERO.feet * S, w * 0.46, h * 0.038, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.restore();

  // A pool of dark behind the figure: the hair is near-white and the orb it is
  // holding is lit, so without this the head dissolves at thumbnail size - and
  // thumbnail size is the only size a cover is ever really seen at.
  ctx.save();
  /*
   * The rect has to be bigger than the gradient's own radius.
   *
   * It was h*2 by h*1.7 around a gradient that reaches zero at 0.9h from a
   * centre 0.4h down - so the top of the falloff fell outside the rect and got
   * cut off, leaving a straight horizontal seam across the sky behind the
   * character's head. A soft shape clipped by a hard rectangle is one of the
   * few canvas mistakes that is invisible while you are writing it and obvious
   * the moment you look at the picture.
   */
  const RADIUS = h * 0.9;
  const backing = ctx.createRadialGradient(cx, top + h * 0.4, 0, cx, top + h * 0.4, RADIUS);
  backing.addColorStop(0, 'rgba(5,9,11,0.52)');
  backing.addColorStop(0.6, 'rgba(5,9,11,0.24)');
  backing.addColorStop(1, 'rgba(5,9,11,0)');
  ctx.fillStyle = backing;
  ctx.fillRect(cx - RADIUS, top + h * 0.4 - RADIUS, RADIUS * 2, RADIUS * 2);
  ctx.restore();

  const dx = Math.round(cx - w / 2);
  const dy = Math.round(top);
  const dw = Math.round(w);
  const dh = Math.round(h);

  /*
   * Rim light, and it comes from below.
   *
   * The brightest thing anywhere near this figure is the object it is holding,
   * so the light wraps UP from the orb rather than down from the sky. Getting
   * that backwards is the kind of mistake nothing reports: the picture still
   * looks finished, it just stops agreeing with itself.
   */
  const figure = document.createElement('canvas');
  figure.width = dw;
  figure.height = dh;
  const fg = figure.getContext('2d')!;
  fg.imageSmoothingEnabled = false;
  fg.drawImage(sheet, SPRITE_FRAME * SPRITE_W, SPRITE_ROW * SPRITE_H, SPRITE_W, SPRITE_H, 0, 0, dw, dh);
  fg.globalCompositeOperation = 'source-in';
  fg.fillStyle = lighten(SPAWN.accent, 0.55);
  fg.fillRect(0, 0, dw, dh);

  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  ctx.globalAlpha = 0.28;
  const r = Math.max(1, Math.round(h * 0.011));
  for (const [ox, oy] of [
    [0, r],
    [-r, r * 0.6],
    [r, r * 0.6],
  ]) {
    ctx.drawImage(figure, dx + (ox ?? 0), dy + (oy ?? 0));
  }
  ctx.restore();

  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(sheet, SPRITE_FRAME * SPRITE_W, SPRITE_ROW * SPRITE_H, SPRITE_W, SPRITE_H, dx, dy, dw, dh);
  ctx.imageSmoothingEnabled = true;
  ctx.restore();

  // The gauntlets, lighting up under what they are holding.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (const side of [-1, 1]) {
    const hx = cx + side * w * 0.46;
    const hy = top + h * 0.6;
    const g = ctx.createRadialGradient(hx, hy, 0, hx, hy, h * 0.17);
    g.addColorStop(0, withAlpha(lighten(SPAWN.accent, 0.7), 0.5));
    g.addColorStop(1, withAlpha(SPAWN.accent, 0));
    ctx.fillStyle = g;
    ctx.fillRect(hx - h * 0.17, hy - h * 0.17, h * 0.34, h * 0.34);
  }
  ctx.restore();
}

/* --------------------------------------------------------------- the orb -- */

/**
 * What the gauntlets are holding.
 *
 * Drawn after the figure and kept genuinely transparent - the body behind it
 * stays visible through the glass - because an opaque sphere is a ball, and the
 * one thing this object has to say is that it contains what you have gathered.
 * So it is built in the order glass actually reads: a wash of colour, the
 * contents, an inner shadow that turns a disc into a sphere, a bright edge
 * where the surface turns away, and two speculars.
 *
 * Nine materials from five regions. That is the only claim the orb needs to
 * make - this is a thing that has been somewhere - and it is the game's own
 * `drawIcon` at small scale, on shells, so the near ones are larger and
 * brighter than the far ones.
 */
const CONTENTS: { id: string; a: number; rr: number; depth: number }[] = [
  { id: 'rimeshard', a: 206, rr: 0.5, depth: 1 },
  { id: 'coolant_residue', a: 318, rr: 0.47, depth: 1 },
  { id: 'heartwood_burl', a: 86, rr: 0.53, depth: 0.95 },
  { id: 'stormpetal', a: 152, rr: 0.33, depth: 0.85 },
  { id: 'sunfused_glass', a: 18, rr: 0.36, depth: 0.85 },
  { id: 'riverglass', a: 262, rr: 0.29, depth: 0.7 },
  { id: 'marshgas_bladder', a: 118, rr: 0.18, depth: 0.55 },
  { id: 'loamstone', a: 342, rr: 0.16, depth: 0.5 },
  { id: 'ashcap_fungus', a: 238, rr: 0.63, depth: 0.45 },
];

function drawOrb(ctx: CanvasRenderingContext2D, S: number): void {
  const cx = ORB.x * S;
  const cy = ORB.y * S;
  const R = ORB.r * S;
  const glass = lighten(GLASS, 0.3);

  // The light it throws, which is what makes it a source rather than a decal.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const halo = ctx.createRadialGradient(cx, cy, 0, cx, cy, R * 2.9);
  halo.addColorStop(0, withAlpha(glass, 0.44));
  halo.addColorStop(0.3, withAlpha(GLASS, 0.17));
  halo.addColorStop(1, withAlpha(GLASS, 0));
  ctx.fillStyle = halo;
  ctx.fillRect(cx - R * 3, cy - R * 3, R * 6, R * 6);
  ctx.restore();

  ctx.save();
  ctx.beginPath();
  ctx.arc(cx, cy, R, 0, Math.PI * 2);
  ctx.clip();

  /*
   * The body of the glass.
   *
   * These alphas are the whole brief. They decide whether the character is
   * visible through the orb, and the answer has to be yes - so the fill never
   * goes above a third, and every bright thing inside is drawn additively so it
   * adds light rather than hiding what is behind it.
   */
  /*
   * A wash of dark first, inside the glass.
   *
   * Transparent does not mean the thing behind it comes through unchanged. The
   * character's tunic is the palest part of the sprite and it sits exactly
   * where the orb is, so with only a colour tint over it the orb came out as a
   * bright rectangle with a faint circle drawn round it - correct alpha
   * compositing, wrong picture. This levels what is behind the glass enough for
   * the sphere to be a sphere, while leaving the figure visible through it,
   * which is the whole point of the object.
   */
  ctx.fillStyle = 'rgba(8,18,12,0.46)';
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);

  const body = ctx.createRadialGradient(cx - R * 0.3, cy - R * 0.35, R * 0.08, cx, cy, R);
  body.addColorStop(0, withAlpha(lighten(GLASS, 0.5), 0.34));
  body.addColorStop(0.55, withAlpha(GLASS, 0.32));
  body.addColorStop(1, withAlpha(darken(GLASS, 0.35), 0.38));
  ctx.fillStyle = body;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);

  // Light IN the glass rather than on it. Without this the sphere is a dark
  // disc with bright things inside, which reads as a hole rather than as a
  // volume full of something.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const lit = ctx.createRadialGradient(cx - R * 0.15, cy - R * 0.1, 0, cx, cy, R * 1.05);
  lit.addColorStop(0, withAlpha(lighten(GLASS, 0.45), 0.6));
  lit.addColorStop(0.5, withAlpha(GLASS, 0.34));
  lit.addColorStop(1, withAlpha(GLASS, 0.14));
  ctx.fillStyle = lit;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);
  ctx.restore();

  for (const item of [...CONTENTS].sort((a, b) => a.depth - b.depth)) {
    const def = material(item.id);
    const a = (item.a * Math.PI) / 180;
    const x = cx + Math.cos(a) * item.rr * R;
    const y = cy + Math.sin(a) * item.rr * R;
    const size = R * 0.3 * (0.55 + item.depth * 0.6);

    ctx.save();
    ctx.globalAlpha = 0.6 + item.depth * 0.4;
    ctx.translate(x, y);
    ctx.rotate(Math.sin(item.a) * 0.4);
    ctx.translate(-size / 2, -size / 2);
    drawIcon(ctx, def.shape, def.color, size);
    ctx.restore();

    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const spark = ctx.createRadialGradient(x, y, 0, x, y, size * 1.5);
    spark.addColorStop(0, withAlpha(def.color, 0.26 * item.depth));
    spark.addColorStop(1, withAlpha(def.color, 0));
    ctx.fillStyle = spark;
    ctx.fillRect(x - size * 1.5, y - size * 1.5, size * 3, size * 3);
    ctx.restore();
  }

  // Suspension, so the inside reads as a volume rather than a collage of icons
  // at different sizes.
  const random = rng(0xabcdef);
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (let i = 0; i < 90; i++) {
    const a = random() * Math.PI * 2;
    const rr = Math.sqrt(random()) * R * 0.92;
    ctx.fillStyle = withAlpha(glass, 0.1 + random() * 0.38);
    ctx.beginPath();
    ctx.arc(cx + Math.cos(a) * rr, cy + Math.sin(a) * rr, (S / 1024) * (0.5 + random() * 1.8), 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();

  // The inner shadow that makes a disc into a sphere.
  const inner = ctx.createRadialGradient(cx, cy, R * 0.55, cx, cy, R);
  inner.addColorStop(0, withAlpha('#07120b', 0));
  inner.addColorStop(1, withAlpha('#07120b', 0.34));
  ctx.fillStyle = inner;
  ctx.fillRect(cx - R, cy - R, R * 2, R * 2);
  ctx.restore();

  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  ctx.lineWidth = R * 0.05;
  const edge = ctx.createLinearGradient(cx - R, cy - R, cx + R, cy + R);
  edge.addColorStop(0, withAlpha(lighten(GLASS, 0.7), 0.62));
  edge.addColorStop(0.45, withAlpha(lighten(GLASS, 0.15), 0.32));
  edge.addColorStop(1, withAlpha(lighten(GLASS, 0.55), 0.75));
  ctx.strokeStyle = edge;
  ctx.beginPath();
  ctx.arc(cx, cy, R * 0.975, 0, Math.PI * 2);
  ctx.stroke();

  // One specular upper left, one bounce lower right. Two is the difference
  // between glass and a coloured circle; three is a bauble.
  ctx.fillStyle = withAlpha('#ffffff', 0.4);
  ctx.beginPath();
  ctx.ellipse(cx - R * 0.42, cy - R * 0.46, R * 0.26, R * 0.15, -0.6, 0, Math.PI * 2);
  ctx.fill();

  const bounce = ctx.createRadialGradient(cx + R * 0.38, cy + R * 0.5, 0, cx + R * 0.38, cy + R * 0.5, R * 0.34);
  bounce.addColorStop(0, withAlpha(lighten(GLASS, 0.7), 0.32));
  bounce.addColorStop(1, withAlpha(GLASS, 0));
  ctx.fillStyle = bounce;
  ctx.fillRect(cx, cy, R, R);
  ctx.restore();
}

/* ------------------------------------------------------------ atmosphere -- */

function drawAir(ctx: CanvasRenderingContext2D, S: number): void {
  const random = rng(0xa11ce);
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (let i = 0; i < 130; i++) {
    const x = random() * S;
    const y = S * 0.3 + random() * S * 0.7;
    // Thickest near the orb, which is where the light is.
    const d = Math.hypot(x - ORB.x * S, y - ORB.y * S) / S;
    if (random() < d * 1.6) continue;
    ctx.fillStyle = withAlpha(random() > 0.4 ? lighten(SPAWN.accent, 0.5) : '#ffffff', 0.12 + random() * 0.3);
    ctx.beginPath();
    ctx.arc(x, y, (0.5 + random() * 1.5) * (S / 1024), 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();

  const v = ctx.createRadialGradient(S * 0.5, S * 0.58, S * 0.26, S * 0.5, S * 0.58, S * 0.88);
  v.addColorStop(0, 'rgba(0,0,0,0)');
  v.addColorStop(0.6, 'rgba(2,6,8,0.24)');
  v.addColorStop(1, 'rgba(2,6,8,0.7)');
  ctx.fillStyle = v;
  ctx.fillRect(0, 0, S, S);
}

/* ------------------------------------------------------------------ type -- */

/** Letterspacing by hand: canvas has no tracking, and a title needs it. */
function tracked(
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  y: number,
  tracking: number,
): void {
  const widths = [...text].map((ch) => ctx.measureText(ch).width);
  const total = widths.reduce((a, b) => a + b, 0) + tracking * (text.length - 1);
  let x = cx - total / 2;
  for (let i = 0; i < text.length; i++) {
    ctx.fillText(text[i] ?? '', x, y);
    x += (widths[i] ?? 0) + tracking;
  }
}

/**
 * The name, across the top.
 *
 * The plate is a gradient rather than a bar: the sky behind the title is
 * already the darkest part of the image, so all it has to do is keep the
 * letterforms off the wall's lit crest, which runs directly under them.
 */
function drawTitle(ctx: CanvasRenderingContext2D, S: number): void {
  const cx = S / 2;

  const plate = ctx.createLinearGradient(0, 0, 0, S * 0.27);
  plate.addColorStop(0, 'rgba(3,6,11,0.82)');
  plate.addColorStop(0.5, 'rgba(3,6,11,0.46)');
  plate.addColorStop(1, 'rgba(3,6,11,0)');
  ctx.fillStyle = plate;
  ctx.fillRect(0, 0, S, S * 0.27);

  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';

  ctx.fillStyle = withAlpha(PULL, 0.78);
  ctx.font = `600 ${S * 0.026}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'PROJECT', cx, S * 0.077, S * 0.023);

  ctx.fillStyle = '#f4f8fc';
  ctx.font = `700 ${S * 0.086}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'MAELSTROM', cx, S * 0.155, S * 0.0125);
}

/* ------------------------------------------------------------------------- */

export async function drawCover(canvas: HTMLCanvasElement, size: number, withTitle: boolean): Promise<void> {
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('no 2d context for the cover');

  const sheet = new Image();
  await new Promise<void>((done, fail) => {
    sheet.onload = () => done();
    sheet.onerror = () => fail(new Error('sprite sheet failed to load'));
    sheet.src = sheetUrl;
  });

  drawSky(ctx, size);
  drawWall(ctx, size);
  drawMountains(ctx, size);
  drawRuin(ctx, size);
  drawGround(ctx, size);
  drawField(ctx, size);
  drawHero(ctx, size, sheet);
  drawOrb(ctx, size);
  drawForeground(ctx, size);
  drawAir(ctx, size);
  if (withTitle) drawTitle(ctx, size);
}

declare global {
  interface Window {
    __drawCover: typeof drawCover;
  }
}

window.__drawCover = drawCover;
