/**
 * The cover art, drawn by the game's own art code.
 *
 * Every mark on this image comes from the build: the character is the real
 * sprite sheet, the creatures are the real `drawCreature`, the materials are
 * the real `drawIcon`, and every colour is read out of `content/`. Nothing is
 * painted by hand and nothing is generated by an image model - which is the
 * whole claim the project makes about its art, and a cover that broke it would
 * be the one piece of art that was not true.
 *
 * The composition is the game stated in one frame:
 *
 * - The maelstrom itself. The gauntlets draw material in along a spiral, and
 *   that pull is the verb the entire world shape is built around. So it is the
 *   hero shape, and the thing the eye lands on.
 * - Four regions in the four corners, in their own palettes, because canon puts
 *   them on the diagonals around a spawn that sits in the middle. The layout of
 *   the image is the layout of the world.
 * - Three creatures out at the edge of the light, already looking at you, with
 *   the awareness markers the player gets over them. The asymmetry, drawn.
 * - One small figure at the centre of all of it, which is the size the player
 *   actually is against a 1.5km arena.
 *
 * Exposed to the tool as `window.__drawCover`, which is the only reason any of
 * this lives outside `web/src`: it must not ship in the game bundle.
 */
import { drawIcon, withAlpha } from '../../web/src/game/icons';
import { drawCreature, type CreatureId } from '../../web/src/game/creatures';
import sheetUrl from '../../web/src/assets/alchemist.png';

interface Biome {
  id: string;
  palette: { ground: string; groundAlt: string; accent: string; fog: string };
}
interface Material {
  id: string;
  shape: string;
  color: string;
  biome: string;
}
interface Bundle {
  biomes: Biome[];
  materials: Material[];
  /** Flattened to one list by the content build; the tiers nesting is source-side. */
  enemies: { id: string; color: string }[];
}

const bundle = (await import('@content/maelstrom-content.json')).default as unknown as Bundle;

const biome = (id: string) => bundle.biomes.find((b) => b.id === id)!;
const material = (id: string) => bundle.materials.find((m) => m.id === id)!;
const enemyColor = (id: string) => bundle.enemies.find((t) => t.id === id)!.color;

/** Sprite sheet geometry, matching tools/make-sprites.mjs. */
const SPRITE_W = 16;
const SPRITE_H = 24;
/** Row 0 is the front-facing walk; frame 0 is the standing pose. */
const SPRITE_ROW = 0;
const SPRITE_FRAME = 0;

/** The pull's colour, taken from the ring the game actually draws. */
const PULL = '#9fd8e8';

/**
 * Deterministic noise, so the cover regenerates byte-identical.
 *
 * A cover that reshuffles every time it is built is a cover nobody can commit,
 * and this one is committed.
 */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

/**
 * The four regions, placed where canon puts them: on the diagonals, around a
 * spawn in the middle. Corners of a square is the same arrangement.
 */
const CORNERS: { id: string; x: number; y: number }[] = [
  { id: 'snowy_mountain', x: 0, y: 0 },
  { id: 'desert', x: 1, y: 0 },
  { id: 'wetland', x: 0, y: 1 },
  { id: 'data_center', x: 1, y: 1 },
];

function drawGround(ctx: CanvasRenderingContext2D, S: number): void {
  const spawn = biome('plains_forest').palette;

  ctx.fillStyle = '#080b07';
  ctx.fillRect(0, 0, S, S);

  // Each corner is its own place, bleeding inward and giving out before the
  // middle: the regions ring the spawn, they do not replace it.
  for (const corner of CORNERS) {
    const p = biome(corner.id).palette;
    const cx = corner.x * S;
    const cy = corner.y * S;
    const grad = ctx.createRadialGradient(cx, cy, 0, cx, cy, S * 0.78);
    grad.addColorStop(0, withAlpha(p.groundAlt, 1));
    grad.addColorStop(0.35, withAlpha(p.ground, 0.74));
    grad.addColorStop(1, withAlpha(p.fog, 0));
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, S, S);

    // A breath of the region's accent right in the corner, which is what tells
    // snow from desert at thumbnail size.
    const tint = ctx.createRadialGradient(cx, cy, 0, cx, cy, S * 0.4);
    tint.addColorStop(0, withAlpha(p.accent, 0.32));
    tint.addColorStop(0.45, withAlpha(p.accent, 0.1));
    tint.addColorStop(1, withAlpha(p.accent, 0));
    ctx.fillStyle = tint;
    ctx.fillRect(0, 0, S, S);
  }

  // The spawn, holding the middle.
  const mid = ctx.createRadialGradient(S / 2, S * 0.46, 0, S / 2, S * 0.46, S * 0.44);
  mid.addColorStop(0, withAlpha(spawn.groundAlt, 0.9));
  mid.addColorStop(0.5, withAlpha(spawn.ground, 0.48));
  mid.addColorStop(1, withAlpha(spawn.fog, 0));
  ctx.fillStyle = mid;
  ctx.fillRect(0, 0, S, S);

  // The ground checker the renderer paints, at cover scale and barely there -
  // enough to keep the large flats from reading as a gradient wallpaper.
  const cell = S / 26;
  ctx.globalAlpha = 0.05;
  for (let y = 0; y < S; y += cell) {
    for (let x = 0; x < S; x += cell) {
      if ((Math.round(x / cell) + Math.round(y / cell)) % 2) continue;
      const q = CORNERS.find((c) => (x < S / 2 ? c.x === 0 : c.x === 1) && (y < S / 2 ? c.y === 0 : c.y === 1))!;
      ctx.fillStyle = biome(q.id).palette.groundAlt;
      ctx.fillRect(x, y, cell, cell);
    }
  }
  ctx.globalAlpha = 1;
}

/** Scattered ground detail, so the flats have some grain in them. */
function drawSpecks(ctx: CanvasRenderingContext2D, S: number): void {
  const random = rng(0x5eed10);
  for (let i = 0; i < 420; i++) {
    const x = random() * S;
    const y = random() * S;
    const q = CORNERS.find((c) => (x < S / 2 ? c.x === 0 : c.x === 1) && (y < S / 2 ? c.y === 0 : c.y === 1))!;
    const p = biome(q.id).palette;
    const r = (0.4 + random() * 1.8) * (S / 1024);
    ctx.fillStyle = withAlpha(random() > 0.7 ? p.accent : p.groundAlt, 0.1 + random() * 0.18);
    ctx.beginPath();
    ctx.ellipse(x, y, r * 2.6, r, 0, 0, Math.PI * 2);
    ctx.fill();
  }
}

/** The arena edge. One thin arc, because "bounded" is a fact worth stating once. */
function drawBoundary(ctx: CanvasRenderingContext2D, S: number, cx: number, cy: number): void {
  ctx.save();
  ctx.strokeStyle = withAlpha(PULL, 0.07);
  ctx.lineWidth = S / 512;
  ctx.beginPath();
  ctx.arc(cx, cy, S * 0.455, 0, Math.PI * 2);
  ctx.stroke();
  ctx.strokeStyle = withAlpha(PULL, 0.04);
  ctx.beginPath();
  ctx.arc(cx, cy, S * 0.482, 0, Math.PI * 2);
  ctx.stroke();
  ctx.restore();
}

const TURNS = 2.15;
/**
 * The arms stop well short of the middle.
 *
 * Run all the way in and they knot into a hairball directly behind the
 * character, who is the one thing on the cover that has to stay readable at
 * thumbnail size. A drain has a clear eye; so does this.
 */
const R_MIN = 0.088;
const R_MAX = 0.47;

/**
 * A point on one arm of the maelstrom, `t` running 0 (rim) to 1 (eye).
 *
 * A true logarithmic spiral - radius falling by a constant factor per turn -
 * rather than a radius eased along a circle. The first attempt did the latter
 * and the arms came out as concentric rings: the radius barely moved for most
 * of their length, so three of them read as a target rather than a drain. In a
 * log spiral the sweep is visible at every radius, which is the whole point of
 * the shape and, given the game's name, of the cover.
 */
function spiralPoint(t: number, offset: number) {
  const theta = t * TURNS * Math.PI * 2;
  const k = Math.log(R_MAX / R_MIN) / (TURNS * Math.PI * 2);
  const r = R_MAX * Math.exp(-k * theta);
  const a = theta + offset;
  return { x: Math.cos(a) * r, y: Math.sin(a) * r, r, theta: a };
}

/**
 * The maelstrom.
 *
 * Drawn additively and several times over at different widths, which is how a
 * canvas gets a glow without a blur filter: the same stroke laid down wide and
 * faint, then narrow and bright.
 */
const ARMS = 5;

function drawSpiral(ctx: CanvasRenderingContext2D, S: number, cx: number, cy: number): void {
  ctx.save();
  ctx.translate(cx, cy);
  ctx.globalCompositeOperation = 'lighter';
  ctx.lineCap = 'round';

  for (let arm = 0; arm < ARMS; arm++) {
    const offset = (arm / ARMS) * Math.PI * 2;
    for (const pass of [
      { width: S * 0.03, alpha: 0.05, color: PULL },
      { width: S * 0.012, alpha: 0.12, color: PULL },
      { width: S * 0.0032, alpha: 0.46, color: '#ffffff' },
    ]) {
      // Each segment is stroked on its own so the arm can fade and taper along
      // its length; one path with one alpha would read as a flat ribbon.
      const STEPS = 320;
      for (let i = 0; i < STEPS; i++) {
        const a = spiralPoint(i / STEPS, offset);
        const b = spiralPoint((i + 1) / STEPS, offset);
        // Brightest where it is about to disappear, faint out at the rim.
        const fade = Math.pow(i / STEPS, 1.5) * 0.9 + 0.1;
        ctx.strokeStyle = withAlpha(pass.color, pass.alpha * fade);
        ctx.lineWidth = pass.width * (0.3 + fade * 0.7);
        ctx.beginPath();
        ctx.moveTo(a.x * S, a.y * S);
        ctx.lineTo(b.x * S, b.y * S);
        ctx.stroke();
      }
    }
  }

  /*
   * The motes: what is actually being pulled in.
   *
   * Drawn as short arcs along the arm rather than dots, because a dot has no
   * direction and the one thing this image has to say is which way everything
   * is travelling.
   */
  const random = rng(0xc0ffee);
  for (let i = 0; i < 300; i++) {
    const offset = (Math.floor(random() * ARMS) / ARMS) * Math.PI * 2 + (random() - 0.5) * 0.3;
    const t = Math.pow(random(), 0.85);
    const p = spiralPoint(t, offset);
    const q = spiralPoint(Math.min(1, t + 0.012 + random() * 0.03), offset);
    const bright = Math.pow(t, 1.3) * 0.85 + 0.15;
    ctx.strokeStyle = withAlpha(random() > 0.55 ? '#ffffff' : PULL, 0.15 + bright * 0.7);
    ctx.lineWidth = (S / 1024) * (0.8 + bright * 3.4) * (0.6 + random() * 0.7);
    ctx.beginPath();
    ctx.moveTo(p.x * S, p.y * S);
    ctx.lineTo(q.x * S, q.y * S);
    ctx.stroke();
  }

  ctx.restore();
}

/**
 * Real material icons, riding the pull in.
 *
 * Placed by hand rather than scattered, and not at random angles: each one sits
 * in the corner of the image belonging to the region it can be gathered from,
 * so the cover states the world's one hard rule - every material is locked to
 * one place - without a caption. The spawn's own three sit nearest the middle,
 * because the middle is what yields eight of the ten elements.
 *
 * Angles dodge the creatures deliberately. An icon landing on a silhouette
 * reads as clutter stuck to it rather than as something in flight.
 */
const CARRIED = [
  // degrees measured with y down, so 270 is straight up
  { id: 'rimeshard', deg: 205, r: 0.325, scale: 1.0 },       // snow, top-left
  { id: 'sunfused_glass', deg: 310, r: 0.315, scale: 0.98 }, // desert, top-right
  { id: 'marshgas_bladder', deg: 112, r: 0.315, scale: 0.9 },// wetland, bottom-left
  { id: 'coolant_residue', deg: 68, r: 0.255, scale: 0.86 }, // data-center, bottom-right
  { id: 'capacitor_core', deg: 132, r: 0.19, scale: 0.6 },
  { id: 'stormpetal', deg: 248, r: 0.21, scale: 0.72 },
  { id: 'heartwood_burl', deg: 158, r: 0.185, scale: 0.6 },
  { id: 'riverglass', deg: 18, r: 0.165, scale: 0.58 },
];

function drawCarried(ctx: CanvasRenderingContext2D, S: number, cx: number, cy: number): void {
  for (const item of CARRIED) {
    const def = material(item.id);
    const a = (item.deg * Math.PI) / 180;
    const x = cx + Math.cos(a) * item.r * S;
    const y = cy + Math.sin(a) * item.r * S;
    const size = S * 0.07 * item.scale;

    ctx.save();
    ctx.translate(x, y);

    // A wash of the item's own colour behind it, so it sits in the light
    // rather than on top of it.
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const glow = ctx.createRadialGradient(0, 0, 0, 0, 0, size * 1.6);
    glow.addColorStop(0, withAlpha(def.color, 0.45));
    glow.addColorStop(1, withAlpha(def.color, 0));
    ctx.fillStyle = glow;
    ctx.fillRect(-size * 1.6, -size * 1.6, size * 3.2, size * 3.2);
    ctx.restore();

    // A short trail behind it, pointing back out along the arm it came in on.
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    const trail = ctx.createLinearGradient(0, 0, Math.cos(a) * size * 2.2, Math.sin(a) * size * 2.2);
    trail.addColorStop(0, withAlpha(def.color, 0.34));
    trail.addColorStop(1, withAlpha(def.color, 0));
    ctx.strokeStyle = trail;
    ctx.lineWidth = size * 0.16;
    ctx.lineCap = 'round';
    ctx.beginPath();
    ctx.moveTo(Math.cos(a) * size * 0.5, Math.sin(a) * size * 0.5);
    ctx.lineTo(Math.cos(a) * size * 2.2, Math.sin(a) * size * 2.2);
    ctx.stroke();
    ctx.restore();

    // A light, consistent tilt: enough to look carried, not enough to look spilled.
    ctx.rotate(Math.sin(item.deg) * 0.16);
    ctx.translate(-size / 2, -size / 2);
    drawIcon(ctx, def.shape, def.color, size);
    ctx.restore();
  }
}

/**
 * The three tiers, out where the light gives up.
 *
 * Each gets the marker the game puts over it, because the player sensing them
 * from 1400 units out while they notice nothing until 90 is the single most
 * characteristic thing about how this world treats you.
 */
const WATCHERS: { id: CreatureId; x: number; y: number; size: number; facing: number }[] = [
  { id: 'goblin', x: 0.2, y: 0.625, size: 0.105, facing: 1 },
  { id: 'minotaur', x: 0.805, y: 0.315, size: 0.155, facing: -1 },
  { id: 'scythe_bearer', x: 0.745, y: 0.695, size: 0.17, facing: -1 },
];

function drawWatchers(ctx: CanvasRenderingContext2D, S: number): void {
  for (const w of WATCHERS) {
    const x = w.x * S;
    const y = w.y * S;
    const size = w.size * S;

    ctx.save();
    ctx.translate(x, y);

    // Standing on something, rather than floating. drawCreature centres its
    // subject on the origin, so the ground is half a body DOWN from it.
    ctx.fillStyle = 'rgba(0,0,0,0.42)';
    ctx.beginPath();
    ctx.ellipse(0, size * 0.47, size * 0.34, size * 0.09, 0, 0, Math.PI * 2);
    ctx.fill();

    ctx.globalAlpha = 0.93;
    drawCreature(ctx, w.id, {
      color: enemyColor(w.id),
      size,
      time: 0,
      phase: 0,
      facing: w.facing,
      windUp: 0,
      stagger: 0,
      aggro: true,
      flash: 0,
    });
    ctx.globalAlpha = 1;

    // The awareness marker, sized by tier the way the HUD sizes it. Kept close
    // to the head: floated any higher it stops belonging to anything.
    const mark = size * 0.085;
    const top = -size * 0.62;
    ctx.fillStyle = withAlpha('#f87171', 0.8);
    ctx.beginPath();
    ctx.moveTo(0, top);
    ctx.lineTo(-mark, top - mark * 1.5);
    ctx.lineTo(mark, top - mark * 1.5);
    ctx.closePath();
    ctx.fill();

    ctx.restore();
  }
}

/** The figure at the eye of it, at the size a person is against 1.5km. */
function drawFigure(ctx: CanvasRenderingContext2D, S: number, sheet: HTMLImageElement, cx: number, cy: number): void {
  const scale = S / 1024;
  const h = 330 * scale;
  const w = (SPRITE_W / SPRITE_H) * h;

  // Standing in the light, not lit from outside it.
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  const bloom = ctx.createRadialGradient(cx, cy, 0, cx, cy, h * 1.15);
  bloom.addColorStop(0, withAlpha(PULL, 0.5));
  bloom.addColorStop(0.35, withAlpha(PULL, 0.16));
  bloom.addColorStop(1, withAlpha(PULL, 0));
  ctx.fillStyle = bloom;
  ctx.fillRect(cx - h * 1.2, cy - h * 1.2, h * 2.4, h * 2.4);
  ctx.restore();

  /*
   * A pool of dark right behind the figure.
   *
   * The character's hair is near-white and the bloom it stands in is near-white
   * too, so without this the head dissolves into the light at thumbnail size -
   * the one thing on the cover that has to stay readable.
   */
  ctx.save();
  const backing = ctx.createRadialGradient(cx, cy, 0, cx, cy, h * 0.62);
  backing.addColorStop(0, 'rgba(6,10,14,0.72)');
  backing.addColorStop(0.62, 'rgba(6,10,14,0.42)');
  backing.addColorStop(1, 'rgba(6,10,14,0)');
  ctx.fillStyle = backing;
  ctx.fillRect(cx - h * 0.7, cy - h * 0.7, h * 1.4, h * 1.4);

  ctx.fillStyle = 'rgba(0,0,0,0.45)';
  ctx.beginPath();
  ctx.ellipse(cx, cy + h * 0.46, w * 0.42, h * 0.055, 0, 0, Math.PI * 2);
  ctx.fill();

  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(
    sheet,
    SPRITE_FRAME * SPRITE_W,
    SPRITE_ROW * SPRITE_H,
    SPRITE_W,
    SPRITE_H,
    Math.round(cx - w / 2),
    Math.round(cy - h * 0.52),
    Math.round(w),
    Math.round(h),
  );
  ctx.imageSmoothingEnabled = true;
  ctx.restore();

  /*
   * Light gathering at both hands.
   *
   * Canon has two half-orbs floating above the gauntlets; the build draws the
   * pull rather than the orbs, so this draws the pull too - a cover should
   * promise what the game does, not what the document says it might.
   */
  ctx.save();
  ctx.globalCompositeOperation = 'lighter';
  for (const side of [-1, 1]) {
    const hx = cx + side * w * 0.42;
    const hy = cy + h * 0.06;
    const g = ctx.createRadialGradient(hx, hy, 0, hx, hy, h * 0.2);
    g.addColorStop(0, withAlpha('#ffffff', 0.85));
    g.addColorStop(0.25, withAlpha(PULL, 0.45));
    g.addColorStop(1, withAlpha(PULL, 0));
    ctx.fillStyle = g;
    ctx.fillRect(hx - h * 0.2, hy - h * 0.2, h * 0.4, h * 0.4);
  }
  ctx.restore();
}

function drawVignette(ctx: CanvasRenderingContext2D, S: number, cx: number, cy: number): void {
  const v = ctx.createRadialGradient(cx, cy, S * 0.22, cx, cy, S * 0.78);
  v.addColorStop(0, 'rgba(0,0,0,0)');
  v.addColorStop(0.62, 'rgba(0,0,0,0.26)');
  v.addColorStop(1, 'rgba(0,0,0,0.7)');
  ctx.fillStyle = v;
  ctx.fillRect(0, 0, S, S);
}

/** Letterspacing by hand: canvas has no tracking, and a title needs it. */
function tracked(
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  y: number,
  tracking: number,
): void {
  const widths = [...text].map((ch) => ctx.measureText(ch).width);
  const total = widths.reduce((a, b) => a + b, 0) + tracking * (text.length - 1);
  let x = cx - total / 2;
  for (let i = 0; i < text.length; i++) {
    ctx.fillText(text[i] ?? '', x, y);
    x += (widths[i] ?? 0) + tracking;
  }
}

/**
 * The name, and nothing else.
 *
 * There was a tagline under this. A cover earns a tagline once the game has
 * settled on what it is promising; until then it is a line of text competing
 * with the only two words that have to be legible at the size a cover is
 * actually seen. Two lines also let the plate sit lower and shorter, so less of
 * the maelstrom is buried under it.
 */
function drawTitle(ctx: CanvasRenderingContext2D, S: number): void {
  const cx = S / 2;

  // A plate under the type, so the title holds against whatever is behind it.
  const plate = ctx.createLinearGradient(0, S * 0.7, 0, S);
  plate.addColorStop(0, 'rgba(6,8,12,0)');
  plate.addColorStop(0.45, 'rgba(6,8,12,0.72)');
  plate.addColorStop(1, 'rgba(6,8,12,0.94)');
  ctx.fillStyle = plate;
  ctx.fillRect(0, S * 0.7, S, S * 0.3);

  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';

  ctx.fillStyle = withAlpha(PULL, 0.72);
  ctx.font = `600 ${S * 0.026}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'PROJECT', cx, S * 0.845, S * 0.022);

  ctx.fillStyle = '#f2f6fb';
  ctx.font = `700 ${S * 0.079}px "Liberation Sans", "DejaVu Sans", sans-serif`;
  tracked(ctx, 'MAELSTROM', cx, S * 0.928, S * 0.0115);
}

export async function drawCover(canvas: HTMLCanvasElement, size: number, withTitle: boolean): Promise<void> {
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('no 2d context for the cover');

  const sheet = new Image();
  await new Promise<void>((done, fail) => {
    sheet.onload = () => done();
    sheet.onerror = () => fail(new Error('sprite sheet failed to load'));
    sheet.src = sheetUrl;
  });

  // Slightly above centre: the title takes the bottom third, and a dead-centre
  // figure would sit on the type.
  const cx = size / 2;
  const cy = size * 0.435;

  drawGround(ctx, size);
  drawSpecks(ctx, size);
  drawBoundary(ctx, size, cx, cy);
  drawWatchers(ctx, size);
  drawSpiral(ctx, size, cx, cy);
  drawCarried(ctx, size, cx, cy);
  drawFigure(ctx, size, sheet, cx, cy);
  drawVignette(ctx, size, cx, cy);
  if (withTitle) drawTitle(ctx, size);
}

declare global {
  interface Window {
    __drawCover: typeof drawCover;
  }
}

window.__drawCover = drawCover;
